import os

# New translation keys to add
new_translations = {
    'tr': {
        "pillar1.f1": "Grundschule, Mittel- und Oberstufe",
        "pillar1.f2": "Tüm yaygın okul derslerinde özel destek",
        "pillar1.f3": "Birebir ve odaklanmış küçük gruplar",
        "pillar1.f4": "BuT devlet yardımı ile tamamen ücretsiz",
        "pillar2.f1": "Almanya'da Lisans ve Yüksek Lisans",
        "pillar2.f2": "Ausbildung (Mesleki Eğitim) yerleşimi",
        "pillar2.f3": "Akademik uygunluk ve vize dosyası",
        "pillar2.f4": "Kişisel dosya rehberliği & danışmanlık",
        "pillar3.f1": "Online Deutschkurse (A1 - C1)",
        "pillar3.f2": "Online Englischkurse (A1 - C1)",
        "pillar3.f3": "Nitelikli eğitim kadrosuyla canlı ders",
        "pillar3.f4": "Türkiye'den esnek saatli katılım modeli",
        
        "calc.labels.duration": "Kalınacak Süre (Ay)",
        "calc.labels.extra": "Aylık Ek Harçlık (Opsiyonel)",
        "calc.val.12months": "12 Ay",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Finansal Oran Dağılımı",
        "calc.res.legend1": "Resmi Bloke Hesap",
        "calc.res.legend2": "İşlem Ücreti",
        "calc.res.totalTitle": "Toplam Gerekli Bütçe",
        "calc.res.monthly": "Aylık Bloke Ödeme:",
        "calc.res.monthlyVal": "992 € / Ay",
        "calc.res.total": "Toplam Bloke Tutar:",
        "calc.res.totalVal": "11.904 €",
        "calc.res.fee": "Kurulum ve İşlem Harcı:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Kabul: ~%15",
        "univ.title.heidelberg": "Heidelberg Üniversitesi",
        "univ.desc.heidelberg": "1386 kuruluş yılıyla Almanya'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.",
        "univ.tag.munich": "📍 MÜNİH",
        "univ.rate.munich": "Kabul: ~%8",
        "univ.title.munich": "Münih Teknik Üniversitesi (TUM)",
        "univ.desc.munich": "Avrupa'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Kabul: ~%20",
        "univ.title.frankfurt": "Goethe Üniversitesi",
        "univ.desc.frankfurt": "Frankfurt'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Temel Başvuru Paketi",
        "price.basic.f1": "Akademik Uygunluk Analizi",
        "price.basic.f2": "Bölüm ve Üniversite Seçimi",
        "price.basic.f3": "3 Üniversiteye Kadar Başvuru",
        "price.basic.f4": "Temel Motivasyon Mektubu Desteği",
        "price.basic.f5": "Vize Görüşmesi Simülasyonu",
        "price.basic.f6": "Almanya Sonrası Destek",
        "price.basic.btn": "Basic Paket Seç",
        "price.plus.badge": "En Çok Tercih Edilen",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Kapsamlı Başvuru & Kabul",
        "price.plus.f1": "Akademik Uygunluk Analizi",
        "price.plus.f2": "5 Üniversiteye Kadar Başvuru",
        "price.plus.f3": "Detaylı Motivasyon & CV Tasarımı",
        "price.plus.f4": "Detaylı Vize Evrak Dosyası Hazırlığı",
        "price.plus.f5": "1 Adet Vize Randevu Simülasyonu",
        "price.plus.f6": "Almanya Sonrası 3 Ay Destek",
        "price.plus.btn": "Plus Paket Seç",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Vize & Varış Garantili VIP",
        "price.premium.f1": "Akademik Uygunluk Analizi",
        "price.premium.f2": "8 Üniversiteye Kadar Başvuru",
        "price.premium.f3": "Genişletilmiş CV & Motivasyon Yazımı",
        "price.premium.f4": "2 Adet Birebir Vize Simülasyonu",
        "price.premium.f5": "Detaylı Konaklama & Yurt Yönlendirmesi",
        "price.premium.f6": "Almanya Sonrası 6 Ay Destek",
        "price.premium.btn": "Premium Paket Seç",
        "price.extra.title": "Ek Hizmetler",
        "price.extra.f1": "Vize Rehberim Paketi",
        "price.extra.f2": "Tek Başvuru Üniversite Paketi",
        "price.extra.f3": "Almanya'ya Varış ve İlk Adımlar",
        "price.extra.f4": "Almanca Hazırlık ve Dil Planlama",
        "price.extra.note": "Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.",
        
        "contact.tag": "Kurumsal İrtibat",
        "contact.title": "Başvurunuzu Planlayın",
        "contact.desc": "Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.",
        "contact.address.title": "Start Akademie UG Merkez Adresi",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Telefon / WhatsApp İrtibat",
        "contact.phone.desc": "0179 7424790",
        "contact.email.title": "Resmi E-Posta",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Kişiselleştirilmiş Randevu Alın",
        "contact.form.desc": "Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.",
        "contact.form.l_name": "Adınız Soyadınız",
        "contact.form.l_phone": "Telefon / WhatsApp",
        "contact.form.l_email": "E-Posta Adresiniz",
        "contact.form.l_service": "Hizmet Alanı",
        "contact.form.l_date": "Görüşme Tarihi",
        "contact.form.btn": "Görüşme Talebi Gönder",
        "contact.bot.title": "StartBotAsistanı",
        "contact.bot.b1": "Bloke Hesap Miktarı",
        "contact.bot.b2": "Ücretsiz BuT Desteği",
        "contact.bot.b3": "Adres & İletişim",
        "contact.form.p_name": "Adınız Soyadınız",
        "contact.form.p_phone": "05XX XXX XX XX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Sorunuzu buraya yazın...",
        
        "footer.services.title": "Hizmetler",
        "footer.services.l1": "Okul Ders Desteği (Nachhilfe)",
        "footer.services.l2": "Üniversite Danışmanlığı",
        "footer.services.l3": "Online Almanca Kursları",
        "footer.services.l4": "Yaz Dil Kampları 2026",
        "footer.corporate.title": "Kurumsal",
        "footer.corporate.l1": "Genel Müdür: Mevlüt Uysal",
        "footer.corporate.l2": "Etüt Merkezi: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Adresi: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Yasal Bilgiler",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau Lisansı",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.",
        "footer.privacy": "Gizlilik Sözleşmesi",
        "footer.terms": "Kullanım Koşulları"
    },
    'en': {
        "pillar1.f1": "Primary, Middle and High School",
        "pillar1.f2": "Special support in all common school subjects",
        "pillar1.f3": "One-on-one and focused small groups",
        "pillar1.f4": "Completely free with BuT government aid",
        "pillar2.f1": "Bachelor's and Master's in Germany",
        "pillar2.f2": "Ausbildung (Vocational Training) placement",
        "pillar2.f3": "Academic eligibility and visa file",
        "pillar2.f4": "Personal file guidance & consulting",
        "pillar3.f1": "Online German Courses (A1 - C1)",
        "pillar3.f2": "Online English Courses (A1 - C1)",
        "pillar3.f3": "Live classes with qualified teaching staff",
        "pillar3.f4": "Flexible attendance model from Turkey",
        
        "calc.labels.duration": "Duration of Stay (Months)",
        "calc.labels.extra": "Monthly Extra Pocket Money (Optional)",
        "calc.val.12months": "12 Months",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Financial Ratio Breakdown",
        "calc.res.legend1": "Official Blocked Account",
        "calc.res.legend2": "Processing Fee",
        "calc.res.totalTitle": "Total Required Budget",
        "calc.res.monthly": "Monthly Blocked Payment:",
        "calc.res.monthlyVal": "992 € / Month",
        "calc.res.total": "Total Blocked Amount:",
        "calc.res.totalVal": "11,904 €",
        "calc.res.fee": "Setup and Processing Fee:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Acceptance: ~15%",
        "univ.title.heidelberg": "Heidelberg University",
        "univ.desc.heidelberg": "Founded in 1386, Germany's oldest and most prestigious university. A global leader in medicine, pharmacy, and natural sciences.",
        "univ.tag.munich": "📍 MUNICH",
        "univ.rate.munich": "Acceptance: ~8%",
        "univ.title.munich": "Technical University of Munich (TUM)",
        "univ.desc.munich": "Europe's technology hub. Ranks among the world's best universities in engineering, computer science, and artificial intelligence.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Acceptance: ~20%",
        "univ.title.frankfurt": "Goethe University",
        "univ.desc.frankfurt": "A leading global research university in the heart of Frankfurt, excelling in economics, finance, social sciences, and humanities.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Basic Application Package",
        "price.basic.f1": "Academic Eligibility Analysis",
        "price.basic.f2": "Department and University Selection",
        "price.basic.f3": "Application to Up to 3 Universities",
        "price.basic.f4": "Basic Motivation Letter Support",
        "price.basic.f5": "Visa Interview Simulation",
        "price.basic.f6": "Post-Germany Support",
        "price.basic.btn": "Choose Basic Package",
        "price.plus.badge": "Most Preferred",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Comprehensive App & Admission",
        "price.plus.f1": "Academic Eligibility Analysis",
        "price.plus.f2": "Application to Up to 5 Universities",
        "price.plus.f3": "Detailed Motivation & CV Design",
        "price.plus.f4": "Detailed Visa Document Prep",
        "price.plus.f5": "1 Visa Appointment Simulation",
        "price.plus.f6": "3 Months Post-Germany Support",
        "price.plus.btn": "Choose Plus Package",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Visa & Arrival Guaranteed VIP",
        "price.premium.f1": "Academic Eligibility Analysis",
        "price.premium.f2": "Application to Up to 8 Universities",
        "price.premium.f3": "Extended CV & Motivation Writing",
        "price.premium.f4": "2 One-on-One Visa Simulations",
        "price.premium.f5": "Detailed Housing & Dorm Guidance",
        "price.premium.f6": "6 Months Post-Germany Support",
        "price.premium.btn": "Choose Premium Package",
        "price.extra.title": "Additional Services",
        "price.extra.f1": "My Visa Guide Package",
        "price.extra.f2": "Single Application University Package",
        "price.extra.f3": "Arrival in Germany and First Steps",
        "price.extra.f4": "German Prep and Language Planning",
        "price.extra.note": "Additional university / program applications may be charged extra.",
        
        "contact.tag": "Corporate Contact",
        "contact.title": "Plan Your Application",
        "contact.desc": "Evaluate your visa & equivalence documents with our expert guides by registering at our education office near Frankfurt or for an online appointment.",
        "contact.address.title": "Start Akademie UG Head Office",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Phone / WhatsApp Contact",
        "contact.phone.desc": "+49 179 7424790",
        "contact.email.title": "Official Email",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Get a Personalized Appointment",
        "contact.form.desc": "Please fill out your information completely. Our education consultants will get back to you within 24 hours.",
        "contact.form.l_name": "Full Name",
        "contact.form.l_phone": "Phone / WhatsApp",
        "contact.form.l_email": "Your Email Address",
        "contact.form.l_service": "Service Area",
        "contact.form.l_date": "Meeting Date",
        "contact.form.btn": "Send Meeting Request",
        "contact.bot.title": "StartBotAssistant",
        "contact.bot.b1": "Blocked Account Amount",
        "contact.bot.b2": "Free BuT Support",
        "contact.bot.b3": "Address & Contact",
        "contact.form.p_name": "Full Name",
        "contact.form.p_phone": "+90 5XX XXX XX XX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Write your question here...",
        
        "footer.services.title": "Services",
        "footer.services.l1": "School Tutoring (Nachhilfe)",
        "footer.services.l2": "University Consulting",
        "footer.services.l3": "Online German Courses",
        "footer.services.l4": "Summer Language Camps 2026",
        "footer.corporate.title": "Corporate",
        "footer.corporate.l1": "General Manager: Mevlüt Uysal",
        "footer.corporate.l2": "Study Center: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Address: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Legal Information",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau License",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). All rights reserved.",
        "footer.privacy": "Privacy Policy",
        "footer.terms": "Terms of Use"
    },
    'de': {
        "pillar1.f1": "Grundschule, Mittel- und Oberstufe",
        "pillar1.f2": "Spezielle Unterstützung in allen gängigen Schulfächern",
        "pillar1.f3": "Einzelunterricht und fokussierte Kleingruppen",
        "pillar1.f4": "Komplett kostenlos mit BuT-Staatshilfe",
        "pillar2.f1": "Bachelor und Master in Deutschland",
        "pillar2.f2": "Ausbildungsvermittlung",
        "pillar2.f3": "Akademische Eignung und Visumsakte",
        "pillar2.f4": "Persönliche Aktenführung & Beratung",
        "pillar3.f1": "Online Deutschkurse (A1 - C1)",
        "pillar3.f2": "Online Englischkurse (A1 - C1)",
        "pillar3.f3": "Live-Unterricht mit qualifiziertem Lehrpersonal",
        "pillar3.f4": "Flexibles Teilnahmemodell aus der Türkei",
        
        "calc.labels.duration": "Aufenthaltsdauer (Monate)",
        "calc.labels.extra": "Monatliches Taschengeld (Optional)",
        "calc.val.12months": "12 Monate",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Finanzielle Aufteilung",
        "calc.res.legend1": "Offizielles Sperrkonto",
        "calc.res.legend2": "Bearbeitungsgebühr",
        "calc.res.totalTitle": "Gesamtes Benötigtes Budget",
        "calc.res.monthly": "Monatliche Sperrzahlung:",
        "calc.res.monthlyVal": "992 € / Monat",
        "calc.res.total": "Gesamter Sperrbetrag:",
        "calc.res.totalVal": "11.904 €",
        "calc.res.fee": "Einrichtungs- und Bearbeitungsgebühr:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Zulassung: ~15%",
        "univ.title.heidelberg": "Universität Heidelberg",
        "univ.desc.heidelberg": "Gegründet 1386, Deutschlands älteste und renommierteste Universität. Weltweit führend in Medizin, Pharmazie und Naturwissenschaften.",
        "univ.tag.munich": "📍 MÜNCHEN",
        "univ.rate.munich": "Zulassung: ~8%",
        "univ.title.munich": "Technische Universität München (TUM)",
        "univ.desc.munich": "Europas Technologie-Hub. Zählt zu den weltbesten Universitäten in Ingenieurwesen, Informatik und Künstlicher Intelligenz.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Zulassung: ~20%",
        "univ.title.frankfurt": "Goethe-Universität",
        "univ.desc.frankfurt": "Führende globale Forschungsuniversität im Herzen von Frankfurt, exzellent in Wirtschaft, Finanzen, Sozial- und Geisteswissenschaften.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Basis-Bewerbungspaket",
        "price.basic.f1": "Akademische Eignungsanalyse",
        "price.basic.f2": "Fach- und Universitätsauswahl",
        "price.basic.f3": "Bewerbung an bis zu 3 Universitäten",
        "price.basic.f4": "Unterstützung beim Basis-Motivationsschreiben",
        "price.basic.f5": "Simulation des Visuminterviews",
        "price.basic.f6": "Betreuung nach Ankunft in Deutschland",
        "price.basic.btn": "Basis-Paket Wählen",
        "price.plus.badge": "Am Beliebtesten",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Umfassende Bewerbung & Zulassung",
        "price.plus.f1": "Akademische Eignungsanalyse",
        "price.plus.f2": "Bewerbung an bis zu 5 Universitäten",
        "price.plus.f3": "Detaillierte Motivations- & Lebenslaufgestaltung",
        "price.plus.f4": "Detaillierte Vorbereitung der Visumsdokumente",
        "price.plus.f5": "1 Visumtermin-Simulation",
        "price.plus.f6": "3 Monate Betreuung nach Ankunft",
        "price.plus.btn": "Plus-Paket Wählen",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Visum & Ankunft Garantiert VIP",
        "price.premium.f1": "Akademische Eignungsanalyse",
        "price.premium.f2": "Bewerbung an bis zu 8 Universitäten",
        "price.premium.f3": "Erweitertes Schreiben von Lebenslauf & Motivation",
        "price.premium.f4": "2 Einzel-Visumsimulationen",
        "price.premium.f5": "Detaillierte Wohnungs- & Wohnheimvermittlung",
        "price.premium.f6": "6 Monate Betreuung nach Ankunft",
        "price.premium.btn": "Premium-Paket Wählen",
        "price.extra.title": "Zusätzliche Dienstleistungen",
        "price.extra.f1": "Mein Visum-Guide Paket",
        "price.extra.f2": "Einzelbewerbung Universitäts-Paket",
        "price.extra.f3": "Ankunft in Deutschland und erste Schritte",
        "price.extra.f4": "Deutschvorbereitung und Sprachplanung",
        "price.extra.note": "Zusätzliche Universitäts- / Programmbewerbungen können extra berechnet werden.",
        
        "contact.tag": "Unternehmenskontakt",
        "contact.title": "Planen Sie Ihre Bewerbung",
        "contact.desc": "Bewerten Sie Ihre Visum- & Äquivalenzdokumente mit unseren Fachberatern, indem Sie sich in unserem Bildungsbüro nahe Frankfurt oder für einen Online-Termin registrieren.",
        "contact.address.title": "Start Akademie UG Hauptsitz",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Telefon / WhatsApp Kontakt",
        "contact.phone.desc": "+49 179 7424790",
        "contact.email.title": "Offizielle E-Mail",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Holen Sie sich einen persönlichen Termin",
        "contact.form.desc": "Bitte füllen Sie Ihre Daten vollständig aus. Unsere Bildungsberater werden sich innerhalb von 24 Stunden bei Ihnen melden.",
        "contact.form.l_name": "Vollständiger Name",
        "contact.form.l_phone": "Telefon / WhatsApp",
        "contact.form.l_email": "Ihre E-Mail-Adresse",
        "contact.form.l_service": "Servicebereich",
        "contact.form.l_date": "Termindatum",
        "contact.form.btn": "Terminanfrage Senden",
        "contact.bot.title": "StartBotAssistent",
        "contact.bot.b1": "Sperrkonto-Betrag",
        "contact.bot.b2": "Kostenlose BuT-Unterstützung",
        "contact.bot.b3": "Adresse & Kontakt",
        "contact.form.p_name": "Vollständiger Name",
        "contact.form.p_phone": "+49 1XX XXXXXXX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Schreiben Sie hier Ihre Frage...",
        
        "footer.services.title": "Dienstleistungen",
        "footer.services.l1": "Schulnachhilfe",
        "footer.services.l2": "Universitätsberatung",
        "footer.services.l3": "Online Deutschkurse",
        "footer.services.l4": "Sommer-Sprachcamps 2026",
        "footer.corporate.title": "Unternehmen",
        "footer.corporate.l1": "Geschäftsführer: Mevlüt Uysal",
        "footer.corporate.l2": "Studienzentrum: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Adresse: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Rechtliche Informationen",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau Lizenz",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). Alle Rechte vorbehalten.",
        "footer.privacy": "Datenschutzvertrag",
        "footer.terms": "Nutzungsbedingungen"
    }
}

import re
import json

# Update lang.js
with open('assets/lang.js', 'r', encoding='utf-8') as f:
    js_content = f.read()

# Parse the JSON from the JS string
json_str = js_content[js_content.find('{'):js_content.rfind('}')+1]
data = json.loads(json_str)

for lang in ['tr', 'en', 'de']:
    data[lang].update(new_translations[lang])

new_js = "const translations = " + json.dumps(data, indent=4, ensure_ascii=False) + ";"
with open('assets/lang.js', 'w', encoding='utf-8') as f:
    f.write(new_js)

# HTML Replacements mapping literal strings to their new keys
replacements = {
    # Pills
    '<li>Grundschule, Mittel- und Oberstufe</li>': '<li data-i18n="pillar1.f1">Grundschule, Mittel- und Oberstufe</li>',
    '<li>Tüm yaygın okul derslerinde özel destek</li>': '<li data-i18n="pillar1.f2">Tüm yaygın okul derslerinde özel destek</li>',
    '<li>Birebir ve odaklanmış küçük gruplar</li>': '<li data-i18n="pillar1.f3">Birebir ve odaklanmış küçük gruplar</li>',
    '<li>BuT devlet yardımı ile tamamen ücretsiz</li>': '<li data-i18n="pillar1.f4">BuT devlet yardımı ile tamamen ücretsiz</li>',
    "<li>Almanya'da Lisans ve Yüksek Lisans</li>": '<li data-i18n="pillar2.f1">Almanya\'da Lisans ve Yüksek Lisans</li>',
    '<li>Ausbildung (Mesleki Eğitim) yerleşimi</li>': '<li data-i18n="pillar2.f2">Ausbildung (Mesleki Eğitim) yerleşimi</li>',
    '<li>Akademik uygunluk ve vize dosyası</li>': '<li data-i18n="pillar2.f3">Akademik uygunluk ve vize dosyası</li>',
    '<li>Kişisel dosya rehberliği & danışmanlık</li>': '<li data-i18n="pillar2.f4">Kişisel dosya rehberliği & danışmanlık</li>',
    '<li>Online Deutschkurse (A1 - C1)</li>': '<li data-i18n="pillar3.f1">Online Deutschkurse (A1 - C1)</li>',
    '<li>Online Englischkurse (A1 - C1)</li>': '<li data-i18n="pillar3.f2">Online Englischkurse (A1 - C1)</li>',
    '<li>Nitelikli eğitim kadrosuyla canlı ders</li>': '<li data-i18n="pillar3.f3">Nitelikli eğitim kadrosuyla canlı ders</li>',
    "<li>Türkiye'den esnek saatli katılım modeli</li>": '<li data-i18n="pillar3.f4">Türkiye\'den esnek saatli katılım modeli</li>',
    
    # Calc
    '<span style="font-weight: 600;">Kalınacak Süre (Ay)</span>': '<span style="font-weight: 600;" data-i18n="calc.labels.duration">Kalınacak Süre (Ay)</span>',
    '<span style="font-weight: 600;">Aylık Ek Harçlık (Opsiyonel)</span>': '<span style="font-weight: 600;" data-i18n="calc.labels.extra">Aylık Ek Harçlık (Opsiyonel)</span>',
    '<span id="duration-val" style="color: var(--primary);">12 Ay</span>': '<span id="duration-val" style="color: var(--primary);" data-i18n="calc.val.12months">12 Ay</span>',
    '<span id="extra-val" style="color: var(--primary);">0 €</span>': '<span id="extra-val" style="color: var(--primary);" data-i18n="calc.val.0eur">0 €</span>',
    '<span style="font-size: 0.95rem; font-weight: 600; color: var(--text-muted); letter-spacing: 1px; text-transform: uppercase;">Finansal Oran Dağılımı</span>': '<span style="font-size: 0.95rem; font-weight: 600; color: var(--text-muted); letter-spacing: 1px; text-transform: uppercase;" data-i18n="calc.res.title">Finansal Oran Dağılımı</span>',
    '<span style="font-size: 0.85rem; color: var(--text-muted);">Resmi Bloke Hesap</span>': '<span style="font-size: 0.85rem; color: var(--text-muted);" data-i18n="calc.res.legend1">Resmi Bloke Hesap</span>',
    '<span style="font-size: 0.85rem; color: var(--text-muted);">İşlem Ücreti</span>': '<span style="font-size: 0.85rem; color: var(--text-muted);" data-i18n="calc.res.legend2">İşlem Ücreti</span>',
    '<span style="font-size: 1.1rem; color: var(--text-muted);">Toplam Gerekli Bütçe</span>': '<span style="font-size: 1.1rem; color: var(--text-muted);" data-i18n="calc.res.totalTitle">Toplam Gerekli Bütçe</span>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Aylık Bloke Ödeme:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.monthly">Aylık Bloke Ödeme:</span>',
    '<strong id="monthly-amount" style="font-size: 1.2rem; color: var(--primary);">992 € / Ay</strong>': '<strong id="monthly-amount" style="font-size: 1.2rem; color: var(--primary);" data-i18n="calc.res.monthlyVal">992 € / Ay</strong>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Toplam Bloke Tutar:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.total">Toplam Bloke Tutar:</span>',
    '<strong id="total-blocked" style="font-size: 1.2rem; color: var(--text);">11.904 €</strong>': '<strong id="total-blocked" style="font-size: 1.2rem; color: var(--text);" data-i18n="calc.res.totalVal">11.904 €</strong>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Kurulum ve İşlem Harcı:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.fee">Kurulum ve İşlem Harcı:</span>',
    '<strong style="font-size: 1.2rem; color: var(--text);">99 €</strong>': '<strong style="font-size: 1.2rem; color: var(--text);" data-i18n="calc.res.feeVal">99 €</strong>',

    # Univ
    '<span class="univ-tag">📍 HEIDELBERG</span>': '<span class="univ-tag" data-i18n="univ.tag.heidelberg">📍 HEIDELBERG</span>',
    '<span class="univ-rate">Kabul: ~%15</span>': '<span class="univ-rate" data-i18n="univ.rate.heidelberg">Kabul: ~%15</span>',
    '<h3>Heidelberg Üniversitesi</h3>': '<h3 data-i18n="univ.title.heidelberg">Heidelberg Üniversitesi</h3>',
    '<p>1386 kuruluş yılıyla Almanya\'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.</p>': '<p data-i18n="univ.desc.heidelberg">1386 kuruluş yılıyla Almanya\'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.</p>',
    '<span class="univ-tag">📍 MÜNİH</span>': '<span class="univ-tag" data-i18n="univ.tag.munich">📍 MÜNİH</span>',
    '<span class="univ-rate">Kabul: ~%8</span>': '<span class="univ-rate" data-i18n="univ.rate.munich">Kabul: ~%8</span>',
    '<h3>Münih Teknik Üniversitesi (TUM)</h3>': '<h3 data-i18n="univ.title.munich">Münih Teknik Üniversitesi (TUM)</h3>',
    '<p>Avrupa\'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.</p>': '<p data-i18n="univ.desc.munich">Avrupa\'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.</p>',
    '<span class="univ-tag">📍 FRANKFURT</span>': '<span class="univ-tag" data-i18n="univ.tag.frankfurt">📍 FRANKFURT</span>',
    '<span class="univ-rate">Kabul: ~%20</span>': '<span class="univ-rate" data-i18n="univ.rate.frankfurt">Kabul: ~%20</span>',
    '<h3>Goethe Üniversitesi</h3>': '<h3 data-i18n="univ.title.frankfurt">Goethe Üniversitesi</h3>',
    '<p>Frankfurt\'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.</p>': '<p data-i18n="univ.desc.frankfurt">Frankfurt\'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.</p>',

    # Pricing
    '<h3>START BASIC</h3>': '<h3 data-i18n="price.basic.tag">START BASIC</h3>',
    '<p>Temel Başvuru Paketi</p>': '<p data-i18n="price.basic.title">Temel Başvuru Paketi</p>',
    '<li>Akademik Uygunluk Analizi</li>': '<li data-i18n="price.basic.f1">Akademik Uygunluk Analizi</li>',
    '<li>Bölüm ve Üniversite Seçimi</li>': '<li data-i18n="price.basic.f2">Bölüm ve Üniversite Seçimi</li>',
    '<li>3 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.basic.f3">3 Üniversiteye Kadar Başvuru</li>',
    '<li>Temel Motivasyon Mektubu Desteği</li>': '<li data-i18n="price.basic.f4">Temel Motivasyon Mektubu Desteği</li>',
    '<li>Vize Görüşmesi Simülasyonu</li>': '<li data-i18n="price.basic.f5">Vize Görüşmesi Simülasyonu</li>',
    '<li>Almanya Sonrası Destek</li>': '<li data-i18n="price.basic.f6">Almanya Sonrası Destek</li>',
    '<a href="#contact" class="btn btn-outline">Basic Paket Seç</a>': '<a href="#contact" class="btn btn-outline" data-i18n="price.basic.btn">Basic Paket Seç</a>',
    
    '<span class="badge">En Çok Tercih Edilen</span>': '<span class="badge" data-i18n="price.plus.badge">En Çok Tercih Edilen</span>',
    '<h3>START PLUS</h3>': '<h3 data-i18n="price.plus.tag">START PLUS</h3>',
    '<p>Kapsamlı Başvuru & Kabul</p>': '<p data-i18n="price.plus.title">Kapsamlı Başvuru & Kabul</p>',
    '<li>5 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.plus.f2">5 Üniversiteye Kadar Başvuru</li>',
    '<li>Detaylı Motivasyon & CV Tasarımı</li>': '<li data-i18n="price.plus.f3">Detaylı Motivasyon & CV Tasarımı</li>',
    '<li>Detaylı Vize Evrak Dosyası Hazırlığı</li>': '<li data-i18n="price.plus.f4">Detaylı Vize Evrak Dosyası Hazırlığı</li>',
    '<li>1 Adet Vize Randevu Simülasyonu</li>': '<li data-i18n="price.plus.f5">1 Adet Vize Randevu Simülasyonu</li>',
    '<li>Almanya Sonrası 3 Ay Destek</li>': '<li data-i18n="price.plus.f6">Almanya Sonrası 3 Ay Destek</li>',
    '<a href="#contact" class="btn btn-primary">Plus Paket Seç</a>': '<a href="#contact" class="btn btn-primary" data-i18n="price.plus.btn">Plus Paket Seç</a>',

    '<h3>START PREMIUM</h3>': '<h3 data-i18n="price.premium.tag">START PREMIUM</h3>',
    '<p>Vize & Varış Garantili VIP</p>': '<p data-i18n="price.premium.title">Vize & Varış Garantili VIP</p>',
    '<li>8 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.premium.f2">8 Üniversiteye Kadar Başvuru</li>',
    '<li>Genişletilmiş CV & Motivasyon Yazımı</li>': '<li data-i18n="price.premium.f3">Genişletilmiş CV & Motivasyon Yazımı</li>',
    '<li>2 Adet Birebir Vize Simülasyonu</li>': '<li data-i18n="price.premium.f4">2 Adet Birebir Vize Simülasyonu</li>',
    '<li>Detaylı Konaklama & Yurt Yönlendirmesi</li>': '<li data-i18n="price.premium.f5">Detaylı Konaklama & Yurt Yönlendirmesi</li>',
    '<li>Almanya Sonrası 6 Ay Destek</li>': '<li data-i18n="price.premium.f6">Almanya Sonrası 6 Ay Destek</li>',
    '<a href="#contact" class="btn btn-outline">Premium Paket Seç</a>': '<a href="#contact" class="btn btn-outline" data-i18n="price.premium.btn">Premium Paket Seç</a>',

    '<h3>Ek Hizmetler</h3>': '<h3 data-i18n="price.extra.title">Ek Hizmetler</h3>',
    '<h4>Vize Rehberim Paketi</h4>': '<h4 data-i18n="price.extra.f1">Vize Rehberim Paketi</h4>',
    '<h4>Tek Başvuru Üniversite Paketi</h4>': '<h4 data-i18n="price.extra.f2">Tek Başvuru Üniversite Paketi</h4>',
    '<h4>Almanya\'ya Varış ve İlk Adımlar</h4>': '<h4 data-i18n="price.extra.f3">Almanya\'ya Varış ve İlk Adımlar</h4>',
    '<h4>Almanca Hazırlık ve Dil Planlama</h4>': '<h4 data-i18n="price.extra.f4">Almanca Hazırlık ve Dil Planlama</h4>',
    '<p>Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.</p>': '<p data-i18n="price.extra.note">Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.</p>',

    # Contact
    '<span class="section-tag">Kurumsal İrtibat</span>': '<span class="section-tag" data-i18n="contact.tag">Kurumsal İrtibat</span>',
    '<h2>Başvurunuzu Planlayın</h2>': '<h2 data-i18n="contact.title">Başvurunuzu Planlayın</h2>',
    '<p>Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.</p>': '<p data-i18n="contact.desc">Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.</p>',
    '<h4>Start Akademie UG Merkez Adresi</h4>': '<h4 data-i18n="contact.address.title">Start Akademie UG Merkez Adresi</h4>',
    '<p>Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main</p>': '<p data-i18n="contact.address.desc">Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main</p>',
    '<h4>Telefon / WhatsApp İrtibat</h4>': '<h4 data-i18n="contact.phone.title">Telefon / WhatsApp İrtibat</h4>',
    '<p>0179 7424790</p>': '<p data-i18n="contact.phone.desc">0179 7424790</p>',
    '<h4>Resmi E-Posta</h4>': '<h4 data-i18n="contact.email.title">Resmi E-Posta</h4>',
    '<p>info@startakademie.de</p>': '<p data-i18n="contact.email.desc">info@startakademie.de</p>',
    
    '<h3>Kişiselleştirilmiş Randevu Alın</h3>': '<h3 data-i18n="contact.form.title">Kişiselleştirilmiş Randevu Alın</h3>',
    '<p>Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.</p>': '<p data-i18n="contact.form.desc">Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.</p>',
    '<label>Adınız Soyadınız</label>': '<label data-i18n="contact.form.l_name">Adınız Soyadınız</label>',
    'placeholder="Adınız Soyadınız"': 'placeholder="Adınız Soyadınız" data-i18n-placeholder="contact.form.p_name"',
    '<label>Telefon / WhatsApp</label>': '<label data-i18n="contact.form.l_phone">Telefon / WhatsApp</label>',
    'placeholder="05XX XXX XX XX"': 'placeholder="05XX XXX XX XX" data-i18n-placeholder="contact.form.p_phone"',
    '<label>E-Posta Adresiniz</label>': '<label data-i18n="contact.form.l_email">E-Posta Adresiniz</label>',
    'placeholder="mail@example.com"': 'placeholder="mail@example.com" data-i18n-placeholder="contact.form.p_email"',
    '<label>Hizmet Alanı</label>': '<label data-i18n="contact.form.l_service">Hizmet Alanı</label>',
    '<label>Görüşme Tarihi</label>': '<label data-i18n="contact.form.l_date">Görüşme Tarihi</label>',
    '<button type="submit" class="btn btn-primary" style="width: 100%;">Görüşme Talebi Gönder</button>': '<button type="submit" class="btn btn-primary" style="width: 100%;" data-i18n="contact.form.btn">Görüşme Talebi Gönder</button>',

    '<h4>StartBotAsistanı</h4>': '<h4 data-i18n="contact.bot.title">StartBotAsistanı</h4>',
    '<span>Bloke Hesap Miktarı</span>': '<span data-i18n="contact.bot.b1">Bloke Hesap Miktarı</span>',
    '<span>Ücretsiz BuT Desteği</span>': '<span data-i18n="contact.bot.b2">Ücretsiz BuT Desteği</span>',
    '<span>Adres & İletişim</span>': '<span data-i18n="contact.bot.b3">Adres & İletişim</span>',
    'placeholder="Sorunuzu buraya yazın..."': 'placeholder="Sorunuzu buraya yazın..." data-i18n-placeholder="contact.form.p_msg"',

    # Footer
    '<p>Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerinin okul başarısını artırırken, Türkiye\'den gelen adayların Almanya devlet üniversitesi başvurularını sıfır vize kaybı politikasıyla koordine eder.</p>': '<p data-i18n="footer.desc">Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerinin okul başarısını artırırken, Türkiye\'den gelen adayların Almanya devlet üniversitesi başvurularını sıfır vize kaybı politikasıyla koordine eder.</p>',
    '<h4>Hizmetler</h4>': '<h4 data-i18n="footer.services.title">Hizmetler</h4>',
    '<li><a href="#nachhilfe-details">Okul Ders Desteği (Nachhilfe)</a></li>': '<li><a href="#nachhilfe-details" data-i18n="footer.services.l1">Okul Ders Desteği (Nachhilfe)</a></li>',
    '<li><a href="#universities">Üniversite Danışmanlığı</a></li>': '<li><a href="#universities" data-i18n="footer.services.l2">Üniversite Danışmanlığı</a></li>',
    '<li><a href="#">Online Almanca Kursları</a></li>': '<li><a href="#" data-i18n="footer.services.l3">Online Almanca Kursları</a></li>',
    '<li><a href="#camp">Yaz Dil Kampları 2026</a></li>': '<li><a href="#camp" data-i18n="footer.services.l4">Yaz Dil Kampları 2026</a></li>',
    
    '<h4>Kurumsal</h4>': '<h4 data-i18n="footer.corporate.title">Kurumsal</h4>',
    '<li><a href="#">Genel Müdür: Mevlüt Uysal</a></li>': '<li><a href="#" data-i18n="footer.corporate.l1">Genel Müdür: Mevlüt Uysal</a></li>',
    '<li><a href="#">Etüt Merkezi: Bahnhofstraße 22</a></li>': '<li><a href="#" data-i18n="footer.corporate.l2">Etüt Merkezi: Bahnhofstraße 22</a></li>',
    '<li><a href="#">UG Adresi: Bahnhofstraße 22 / 22a</a></li>': '<li><a href="#" data-i18n="footer.corporate.l3">UG Adresi: Bahnhofstraße 22 / 22a</a></li>',
    '<li><a href="#">Instagram: @startakademie</a></li>': '<li><a href="#" data-i18n="footer.corporate.l4">Instagram: @startakademie</a></li>',
    
    '<h4>Yasal Bilgiler</h4>': '<h4 data-i18n="footer.legal.title">Yasal Bilgiler</h4>',
    '<li><a href="#">Impressum</a></li>': '<li><a href="#" data-i18n="footer.legal.l1">Impressum</a></li>',
    '<li><a href="#">Datenschutzerklärung</a></li>': '<li><a href="#" data-i18n="footer.legal.l2">Datenschutzerklärung</a></li>',
    '<li><a href="#">Anerkannter Lernförderanbieter</a></li>': '<li><a href="#" data-i18n="footer.legal.l3">Anerkannter Lernförderanbieter</a></li>',
    '<li><a href="#">Kreis Groß-Gerau Lisansı</a></li>': '<li><a href="#" data-i18n="footer.legal.l4">Kreis Groß-Gerau Lisansı</a></li>',
    
    '<p>© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.</p>': '<p data-i18n="footer.copy">© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.</p>',
    '<a href="#">Gizlilik Sözleşmesi</a>': '<a href="#" data-i18n="footer.privacy">Gizlilik Sözleşmesi</a>',
    '<a href="#">Kullanım Koşulları</a>': '<a href="#" data-i18n="footer.terms">Kullanım Koşulları</a>',
}

with open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

for k, v in replacements.items():
    html = html.replace(k, v)

with open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Translation update complete! Added to lang.js and index.html")
