# Read existing lang.js content (I will just hardcode the merged dictionaries)
import json
import codecs

old_tr = {
        "nav.home": "Home",
        "nav.programs": "Programlar",
        "nav.universities": "Üniversiteler",
        "nav.consulting": "Danışmanlık",
        "nav.test": "Denklik Testi",
        "nav.camp": "Sommercamp",
        "nav.contact": "İletişim",
        "nav.meeting": "Ön Görüşme",
        
        "hero.main_title": "Almanya'da <em>Eğitim Yolunuz</em>",
        "hero.seo_desc": "Almanya'da Eğitim, Nachhilfe ve Üniversite Kabul Danışmanlığı Merkezi",
        
        "hero.title": "Almanya'da Eğitim Yolunuz <em>Burada Başlar</em>",
        "hero.subtitle": "Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerine (Nachhilfe) okul başarısı kazandırırken, Türkiye'den gelen adayların Almanya üniversitesi başvurularını sıfır vize kaybı hedefiyle koordine eder.",
        "hero.btn1": "Eğitim Alanları",
        "hero.btn2": "Kabul Danışmanlığı",
        "hero.scroll": "Aşağı Kaydırın",
        
        "welcome.tag": "AKADEMİK KÖPRÜ",
        "welcome.title": "Resmi Kabul ve <em>Vize Danışmanlığı</em>",
        "welcome.desc": "Eğitim yolculuğunuzu riske atmayın. Akademik denklik analizinden resmi vize dosyanızın mükemmelleştirilmesine kadar tüm aşamaları uzman kadromuzla güvence altına alıyoruz.",
        "welcome.stat1": "%98",
        "welcome.stat1_desc": "KABUL ORANI",
        "welcome.stat2": "VNN",
        "welcome.stat2_desc": "AKREDİTE KALİTE",
        
        "pillars.tag": "START PROGRAMLARI",
        "pillars.title": "Geleceğe Ulaşan Üç Eğitim Kanadı",
        "pillars.desc": "Almanya yerelindeki okul desteklerinden, üniversite kabul ve hazırlık kurslarına kadar hedefinize özel kurumsal eğitim çözümlerimiz.",
        "pillar1.title": "Nachhilfe <em>in Deutschland</em>",
        "pillar1.tag": "Almanca Odaklı",
        "pillar1.btn": "Ders Desteği Başvurusu",
        "pillar2.title": "Bildungsberatung <em>für Deutschland</em>",
        "pillar2.tag": "Aday Odaklı / Türkçe 🇹🇷",
        "pillar2.btn": "Kabul Danışmanlığı Keşfet",
        "pillar3.title": "Online <em>Sprachkurse</em>",
        "pillar3.tag": "Türkçe Ağırlıklı / Canlı 🇹🇷",
        "pillar3.btn": "Dil Kursuna Kaydol",

        "nachhilfe.tag": "Bireysel Gelişim",
        "nachhilfe.title": "Rüsselsheim'da Ders Desteği",
        "nachhilfe.desc": "Daha iyi notlar, okul hayatında daha fazla özgüven ve motivasyon için çocuğunuzu esnek, kişisel ve hedefe yönelik olarak destekliyoruz.",
        "nachhilfe.subjects.title": "1-13. Sınıflar İçin Dersler",
        "nachhilfe.subjects.group1": "1. Temel Dersler",
        "nachhilfe.subjects.group2": "2. Fen Bilimleri",
        "nachhilfe.subjects.group3": "3. Diğer Dersler ve Okul Türleri",
        "nachhilfe.subjects.group3_desc": "Tarih, Fransızca, İspanyolca, Latince, DaF.<br><strong>İlkokuldan liseye kadar.</strong>",
        "nachhilfe.models.title": "Ders Modellerimiz",
        "nachhilfe.models.m1": "Birebir ve Küçük Gruplar",
        "nachhilfe.models.m1_desc": "Çocuğunuzun ihtiyaçlarına tam uyumlu bireysel destek.",
        "nachhilfe.models.m2": "Tandem Eğitimi",
        "nachhilfe.models.m2_desc": "İki öğrenci, tek hedef. Birlikte öğrenin, birlikte ilerleyin.",
        "nachhilfe.models.m3": "Ödev Takibi",
        "nachhilfe.models.m3_desc": "Ödevlere destek oluyor ve daha fazla güven sağlıyoruz.",
        "nachhilfe.models.m4": "Sınav ve Test Hazırlığı",
        "nachhilfe.models.m4_desc": "Yazılılara ve bitirme sınavlarına yönelik hedefli hazırlık.",
        "nachhilfe.models.m5": "Online Eğitim",
        "nachhilfe.models.m5_desc": "Esnek öğrenim – birebir derslerle evinizin rahatlığında.",
        
        "flat.tag": "YENİ",
        "flat.title": "Sınırsız Ödev Desteği (Flat) <span style='color: var(--gold);'>150 € / Ay</span>",
        "flat.subtitle": "<strong>3.-8. Sınıf</strong> öğrencileri için. Haftada 4 gün.",
        "flat.p1": "Sabit saatler & net yapı",
        "flat.p2": "Doğruluk ve eksiksizlik kontrolü",
        "flat.p3": "Bağımsız çalışmayı teşvik",
        "flat.steps.title": "Sürecin İşleyişi:",
        "flat.step1": "<strong>Geliş:</strong> Sabit saatlerde kuruma varış.",
        "flat.step2": "<strong>Bağımsız çalışma:</strong> Ödevlerin sessizce yapılması.",
        "flat.step3": "<strong>Destek:</strong> Eğitmenlerin sorulara yanıt vermesi.",
        "flat.step4": "<strong>Kontrol:</strong> Doğruluk teyidi.",
        "flat.step5": "<strong>Bitti mi?:</strong> Çocuğun eve dönmesi.",
        "flat.step6": "<strong>Ödev Yok mu?:</strong> Anlamlı çalışmalar (Okuma, test).",

        "but.tag": "Eğitim ve Katılım (BuT)",
        "but.title": "Çocuğunuz İçin Ücretsiz Ders Desteği!",
        "but.desc": "BuT başvurunuzda size yardımcı oluyor ve çocuğunuzun öğrenim başarısına eşlik ediyoruz.",
        "but.who.title": "BuT desteğini kimler alabilir?",
        "but.who.p1": "Vatandaşlık Geliri (Bürgergeld)",
        "but.who.p2": "Kira Yardımı (Wohngeld)",
        "but.who.p3": "Çocuk Ek Ödeneği (Kinderzuschlag)",
        "but.who.p4": "Sosyal Yardım / Sığınmacı Ödenekleri",
        "but.how.title": "BuT Başvurusu (6 Adımda)",
        "but.how.s1": "Formu bizden isteyin veya teslim alın",
        "but.how.s2": "Formu doldurun",
        "but.how.s3": "Okul, onayı tamamlar",
        "but.how.s4": "Belgeleri ilgili makama gönderin",
        "but.how.s5": "Onayı alın",
        "but.how.s6": "Belge ile Start Akademie'ye kaydolun",

        "calc.tag": "BLOKE HESAP HESAPLAYICI",
        "calc.title": "Sperrkonto Finansal Planlayıcı",
        "calc.desc": "Almanya'da eğitim vizesi alabilmeniz için kanıtlamanız gereken güncel Bloke Hesap (Sperrkonto) miktarını belirleyin. Resmi referans tutar aylık 992 €'dur.",
        "calc.months": "Kalınacak Süre (Ay)",
        "calc.extra": "Aylık Ek Harçlık (Opsiyonel)",
        
        "univ.tag": "ALMAN DEVLET ÜNİVERSİTELERİ",
        "univ.title": "Geleceğinizi Şekillendiren Kampüsler",
        "univ.desc": "YÖK denkliği olan, dünya sıralamalarında üst seviyedeki ve harçsız Alman Devlet Üniversitelerine şartlı kabul başvurularınızı gerçekleştiriyoruz.",
        
        "price.tag": "PAKET VE HİZMETLER",
        "price.title": "Resmi Danışmanlık Paketleri",
        "price.desc": "Denklik analizinden vize randevu simülasyonuna kadar ihtiyacınıza uygun kapsamlı başvuru ve vize rehberliği paketlerimiz.",

        "wizard.tag": "Hızlı Denklik Testi",
        "wizard.title": "Almanya Üniversite Uygunluk Sihirbazı",
        "wizard.desc": "Lise mezuniyet bilginize göre doğrudan Almanya devlet üniversitesine kabul alıp alamayacağınızı 4 adımda hızlıca kontrol edin.",
        "wizard.step1.q": "1. Mezun olduğunuz / olacağınız lise türü hangisidir?",
        "wizard.step1.o1": "Anadolu veya Fen Lisesi",
        "wizard.step1.o2": "Meslek veya İmam Hatip Lisesi",
        "wizard.step2.q": "2. Uluslararası bir diplomanız var mı? (IB, Abitur, AP vb.)",
        "wizard.step2.o1": "Evet (IB / Abitur / AP mevcut)",
        "wizard.step2.o2": "Hayır (Sadece YKS / Lise Diploması)",
        "wizard.step3.q": "3. Güncel Almanca dil seviyeniz nedir?",
        "wizard.step3.o1": "B1 ve Üzeri",
        "wizard.step3.o2": "Başlangıç Seviyesi / Hiç Yok",
        "wizard.step4.q": "4. YKS sınavına girdiniz mi ve bir üniversiteye yerleştiniz mi?",
        "wizard.step4.o1": "Evet, 4 yıllık bölüme yerleştim",
        "wizard.step4.o2": "Hayır, henüz girmedim/yerleşmedim",
        "wizard.loading": "Değerlendiriliyor...",
        "wizard.btn": "Birebir Analiz Randevusu Alın",

        "camp.tag": "Abitur & Oberstufe Boost",
        "camp.title": "Yaz Kampları & Yoğunlaştırılmış Kurslar 2026",
        "camp.desc": "Lise eğitimine veya Abitur'a yönelik özel hazırlanın - ister Rüsselsheim'da yüz yüze yoğun, ister online esnek birebir derslerle.",
        "camp.inperson.tag": "Yüz Yüze Yoğunlaştırılmış Kamp",
        "camp.inperson.title": "12. Sınıfa Güçlü Başlangıç",
        "camp.inperson.desc": "12. sınıfa geçiş hayati bir adımdır. Yoğunlaştırılmış kampımızla öğrencileri lise (Oberstufe) gereksinimlerine özel olarak hazırlıyoruz.",
        "camp.inperson.f1": "Matematik (Lise İleri Düzey)",
        "camp.inperson.f2": "Almanca: Analiz & Yazma Eğitimi",
        "camp.inperson.f3": "İngilizce: Makale & Metin Analizi",
        "camp.inperson.f4": "Sınav Eğitimi & Öğrenme Stratejileri",
        "camp.inperson.dates": "2026 Kamp Tarihleri",
        "camp.inperson.d1": "Cumartesi, 25.07.2026",
        "camp.inperson.d2": "Cumartesi, 01.08.2026",
        "camp.inperson.d3": "Cumartesi, 15.08.2026",
        "camp.inperson.d4": "Cumartesi, 22.08.2026",
        "camp.inperson.info1": "Saat 09:00 - 16:30 arası",
        "camp.inperson.info2": "5 ile maks. 8 katılımcı",
        "camp.inperson.info3": "Start Akademie - Rüsselsheim",
        "camp.inperson.btn": "Şimdi Yer Ayırtın",
        "camp.online.title": "Online İngilizce Yaz Kursları (1:1)",
        "camp.online.desc": "4 Hafta (06.07. – 31.07.2026) | Pazartesiden Cumaya, her gün 90 dk | 20 Ders Birimi",
        "camp.class11.tag": "11. Sınıf",
        "camp.class11.title": "Lise İleri Düzey Hazırlık",
        "camp.class11.p1": "<strong>Dilbilgisi & Yazma:</strong> Zamanlar, Edilgen Çatı, Makaleler.",
        "camp.class11.p2": "<strong>Metin Analizi & Edebiyat:</strong> Kısa öykü ve roman.",
        "camp.class11.p3": "<strong>Kültür & Medya:</strong> İngiltere/ABD politikasını anlama.",
        "camp.class11.p4": "<strong>Argümantasyon:</strong> Görüşleri gerekçelendirme.",
        "camp.class12.tag": "12. Sınıf",
        "camp.class12.title": "Yeterlilik Aşaması",
        "camp.class12.p1": "<strong>Metin Analizi:</strong> Karmaşık metinler, Shakespeare.",
        "camp.class12.p2": "<strong>Akademik Yazım:</strong> Üst düzey yorum ve tartışma.",
        "camp.class12.p3": "<strong>Medya & Politika:</strong> Küresel konuları değerlendirme.",
        "camp.class12.p4": "<strong>Arabuluculuk (Mediation):</strong> İçerikleri aktarma.",
        "camp.class13.tag": "13. Sınıf",
        "camp.class13.title": "Final Abitur Desteği",
        "camp.class13.p1": "<strong>Söylem Analizi:</strong> Retorik analiz ve sentez.",
        "camp.class13.p2": "<strong>Abitur Yazımı:</strong> Sınav koşullarında keskinlik.",
        "camp.class13.p3": "<strong>Toplum:</strong> Demokrasi ve kimliği eleştirel analiz.",
        "camp.class13.p4": "<strong>Argümantasyon:</strong> Karşıt görüşleri entegre etme.",
        "camp.online.btn": "Yaz Kursu Kaydı Oluştur",

        "visa.tag": "Önemli Bilgilendirme",
        "visa.title": "Öğrenci Vizesi ve Çalışma Hakkı",
        "visa.desc": "Almanya'da eğitim planlayan öğrenciler için vize süreci, finansman ve resmi evrak hazırlığı büyük önem taşır.",
        "visa.item1.title": "1. Öğrenci Vizesi",
        "visa.item1.desc": "Genellikle kabul belgesi, pasaport, finansman kanıtı (Sperrkonto), sağlık sigortası ve akademik belgeler gerekir.",
        "visa.item2.title": "2. Çalışma Hakkı",
        "visa.item2.desc": "Uluslararası öğrenciler Almanya'da yılda <strong>140 tam gün</strong> veya <strong>280 yarım gün</strong> çalışma hakkına sahiptir.",
        "visa.item3.title": "3. Oturum Süreci",
        "visa.item3.desc": "Eğitim amacıyla verilen oturum izni, öğrenim sürecine bağlı olarak uzatılabilir.",
        "visa.item4.title": "4. Mezuniyet Sonrası",
        "visa.item4.desc": "Mezunlar, uygun koşullarda iş arama süresi ve sonrasında çalışma oturumuna geçiş imkânına sahip olabilir.",
        "visa.warning": "<strong>Uyarı:</strong> Vize kararı yalnızca yetkili resmi makamlar tarafından verilir. Başvuru dosyasının eksiksiz hazırlanması bu süreçte büyük önem taşır.",

        "faq.title": "Sık Sorulan Sorular",
        "faq.q1": "1. Almanya'da üniversite tamamen ücretsiz mi?",
        "faq.a1": "Birçok devlet üniversitesinde yüksek öğrenim harcı yoktur; ancak dönemlik katkı payı ve yaşam giderleri ayrıca planlanmalıdır.",
        "faq.q2": "2. YKS olmadan başvuru yapılabilir mi?",
        "faq.a2": "Bu durum öğrencinin eğitim geçmişine göre değişir. Her dosya bireysel değerlendirilmelidir.",
        "faq.q3": "3. Almanca bilmeden başvuru mümkün mü?",
        "faq.a3": "Bazı öğrenciler için dil kursu, şartlı kabul veya hazırlık seçenekleri değerlendirilebilir.",
        "faq.q4": "4. Öğrenciler Almanya'da çalışabilir mi?",
        "faq.a4": "Evet, resmi kurallar çerçevesinde yılda 140 tam gün veya 280 yarım gün çalışma hakkı bulunabilir.",
        "faq.q5": "5. Start Akademie kabul veya vize garantisi verir mi?",
        "faq.a5": "Hayır. Nihai karar ilgili üniversite ve resmi makamlar tarafından verilir.",

        "footer.desc": "Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerinin okul başarısını artırırken, Türkiye'den gelen adayların Almanya devlet üniversitesi başvurularını sıfır vize kaybı politikasıyla koordine eder."
}

old_en = {
        "nav.home": "Home",
        "nav.programs": "Programs",
        "nav.universities": "Universities",
        "nav.consulting": "Consulting",
        "nav.test": "Equivalence Test",
        "nav.camp": "Summer Camp",
        "nav.contact": "Contact",
        "nav.meeting": "Book Meeting",
        
        "hero.main_title": "Your Education Path <em>in Germany</em>",
        "hero.seo_desc": "Your Premium Guide for Education, Tutoring, and University Admission in Germany",
        
        "hero.title": "Your Education Journey in Germany <em>Starts Here</em>",
        "hero.subtitle": "Start Akademie, with its center near Frankfurt, increases the school success (Nachhilfe) of high school students and coordinates the German public university applications of candidates from Turkey with a zero-visa-loss policy.",
        "hero.btn1": "Education Fields",
        "hero.btn2": "Admission Consulting",
        "hero.scroll": "Scroll Down",
        
        "welcome.tag": "ACADEMIC BRIDGE",
        "welcome.title": "Official Admission & <em>Visa Consulting</em>",
        "welcome.desc": "Don't risk your education journey. From academic equivalence analysis to perfecting your official visa file, we secure all stages with our expert staff.",
        "welcome.stat1": "98%",
        "welcome.stat1_desc": "ACCEPTANCE RATE",
        "welcome.stat2": "VNN",
        "welcome.stat2_desc": "ACCREDITED QUALITY",
        
        "pillars.tag": "START PROGRAMS",
        "pillars.title": "Three Wings Reaching the Future",
        "pillars.desc": "Corporate educational solutions tailored to your goals, from local school support in Germany to university admission and preparation courses.",
        "pillar1.title": "Tutoring <em>in Germany</em>",
        "pillar1.tag": "German Speaking Area",
        "pillar1.btn": "Apply for Tutoring",
        "pillar2.title": "Education Consulting <em>for Germany</em>",
        "pillar2.tag": "Candidate Focused / Turkish 🇹🇷",
        "pillar2.btn": "Explore Admission Consulting",
        "pillar3.title": "Online <em>Language Courses</em>",
        "pillar3.tag": "Turkish Focus / Live 🇹🇷",
        "pillar3.btn": "Register for Language Course",

        "nachhilfe.tag": "Individual Support",
        "nachhilfe.title": "Tutoring in Rüsselsheim",
        "nachhilfe.desc": "We support your child flexibly, personally, and in a goal-oriented way – for better grades, more confidence, and more motivation in everyday school life.",
        "nachhilfe.subjects.title": "Subjects for Grades 1–13",
        "nachhilfe.subjects.group1": "1. Core Subjects",
        "nachhilfe.subjects.group2": "2. Sciences",
        "nachhilfe.subjects.group3": "3. Other Subjects & Types",
        "nachhilfe.subjects.group3_desc": "History, French, Spanish, Latin, DaF.<br><strong>From primary to high school.</strong>",
        "nachhilfe.models.title": "Our Teaching Models",
        "nachhilfe.models.m1": "One-on-One & Small Groups",
        "nachhilfe.models.m1_desc": "Individual support tailored to your child's needs.",
        "nachhilfe.models.m2": "Tandem Tutoring",
        "nachhilfe.models.m2_desc": "Two students, one goal. Learn together, progress together.",
        "nachhilfe.models.m3": "Homework Support",
        "nachhilfe.models.m3_desc": "We assist with homework and build confidence.",
        "nachhilfe.models.m4": "Exam & Test Preparation",
        "nachhilfe.models.m4_desc": "Targeted preparation for exams and graduations.",
        "nachhilfe.models.m5": "Online Classes",
        "nachhilfe.models.m5_desc": "Flexible learning - also from home, in one-on-one sessions.",
        
        "flat.tag": "NEW",
        "flat.title": "Homework Flat-Rate <span style='color: var(--gold);'>150 € / Month</span>",
        "flat.subtitle": "For students in <strong>grades 3–8</strong>. 4x a week.",
        "flat.p1": "Fixed times & clear structure",
        "flat.p2": "Checked for correctness",
        "flat.p3": "Promoting independent work",
        "flat.steps.title": "Process overview:",
        "flat.step1": "<strong>Arrival:</strong> Fixed times for support.",
        "flat.step2": "<strong>Independent work:</strong> Doing homework quietly.",
        "flat.step3": "<strong>Support:</strong> Teachers help with questions.",
        "flat.step4": "<strong>Control:</strong> Checking for correctness.",
        "flat.step5": "<strong>Done?:</strong> Child is allowed to go home.",
        "flat.step6": "<strong>No homework?:</strong> Meaningful practice.",

        "but.tag": "Education & Participation (BuT)",
        "but.title": "Free Tutoring for Your Child!",
        "but.desc": "We assist you with the BuT application and guide your child to learning success.",
        "but.who.title": "Who can get BuT?",
        "but.who.p1": "Citizen's Benefit (Bürgergeld)",
        "but.who.p2": "Housing Allowance (Wohngeld)",
        "but.who.p3": "Child Supplement (Kinderzuschlag)",
        "but.who.p4": "Social Assistance / Asylum Benefits",
        "but.how.title": "How to apply for BuT (6 steps)",
        "but.how.s1": "Request or pick up the form from us",
        "but.how.s2": "Fill out the application",
        "but.how.s3": "School completes the confirmation",
        "but.how.s4": "Send documents to the office",
        "but.how.s5": "Receive approval",
        "but.how.s6": "Register at Start Akademie",

        "calc.tag": "BLOCKED ACCOUNT CALCULATOR",
        "calc.title": "Sperrkonto Financial Planner",
        "calc.desc": "Determine the current Blocked Account (Sperrkonto) amount you need to prove to get an education visa in Germany. Official reference amount is 992 €/month.",
        "calc.months": "Duration of Stay (Months)",
        "calc.extra": "Monthly Extra Allowance (Optional)",
        
        "univ.tag": "GERMAN PUBLIC UNIVERSITIES",
        "univ.title": "Campuses Shaping Your Future",
        "univ.desc": "We carry out your conditional admission applications to tuition-free German Public Universities that have YÖK equivalence and rank high globally.",
        
        "price.tag": "PACKAGES AND SERVICES",
        "price.title": "Official Consulting Packages",
        "price.desc": "Comprehensive application and visa guidance packages suited to your needs, from equivalence analysis to visa interview simulation.",

        "wizard.tag": "Quick Equivalence Test",
        "wizard.title": "Germany University Suitability Wizard",
        "wizard.desc": "Quickly check in 4 steps if you can get direct admission to a German public university based on your high school graduation.",
        "wizard.step1.q": "1. What type of high school are you graduating from?",
        "wizard.step1.o1": "Anatolian or Science High School",
        "wizard.step1.o2": "Vocational or Imam Hatip High School",
        "wizard.step2.q": "2. Do you have an international diploma? (IB, Abitur, AP etc.)",
        "wizard.step2.o1": "Yes (IB / Abitur / AP available)",
        "wizard.step2.o2": "No (Only YKS / High School Diploma)",
        "wizard.step3.q": "3. What is your current German language level?",
        "wizard.step3.o1": "B1 and Above",
        "wizard.step3.o2": "Beginner / None",
        "wizard.step4.q": "4. Have you taken the YKS exam and been placed in a university?",
        "wizard.step4.o1": "Yes, placed in a 4-year program",
        "wizard.step4.o2": "No, not taken/placed yet",
        "wizard.loading": "Evaluating...",
        "wizard.btn": "Book a 1-on-1 Analysis Meeting",

        "camp.tag": "Abitur & Oberstufe Boost",
        "camp.title": "Summer Camps & Intensive Courses 2026",
        "camp.desc": "Prepare specifically for the Oberstufe or Abitur – either intensively on-site in Rüsselsheim or flexibly in online one-on-one lessons.",
        "camp.inperson.tag": "Intensive On-site Camp",
        "camp.inperson.title": "Strong Start into 12th Grade",
        "camp.inperson.desc": "The transition to 12th grade is a crucial step. With our intensive camp, we specifically prepare students for the requirements of the upper school.",
        "camp.inperson.f1": "Mathematics Upper School",
        "camp.inperson.f2": "German: Analysis & Writing",
        "camp.inperson.f3": "English: Essay & Text Analysis",
        "camp.inperson.f4": "Exam Training & Strategies",
        "camp.inperson.dates": "Camp Dates 2026",
        "camp.inperson.d1": "Saturday, 25.07.2026",
        "camp.inperson.d2": "Saturday, 01.08.2026",
        "camp.inperson.d3": "Saturday, 15.08.2026",
        "camp.inperson.d4": "Saturday, 22.08.2026",
        "camp.inperson.info1": "09:00 - 16:30 hrs",
        "camp.inperson.info2": "5 to max. 8 participants",
        "camp.inperson.info3": "Start Akademie - Rüsselsheim",
        "camp.inperson.btn": "Request a Spot Now",
        "camp.online.title": "Online Summer Courses English (1:1)",
        "camp.online.desc": "4 Weeks (06.07. – 31.07.2026) | Monday to Friday, 90 mins daily | 20 Lessons",
        "camp.class11.tag": "11th Grade",
        "camp.class11.title": "Preparation for Upper School",
        "camp.class11.p1": "<strong>Grammar & Writing:</strong> Tenses, Passive, Essays.",
        "camp.class11.p2": "<strong>Text Analysis:</strong> Interpreting short stories, novels.",
        "camp.class11.p3": "<strong>Culture & Media:</strong> Understanding UK/US politics.",
        "camp.class11.p4": "<strong>Argumentation:</strong> Justifying standpoints.",
        "camp.class12.tag": "12th Grade",
        "camp.class12.title": "Qualification Phase",
        "camp.class12.p1": "<strong>Text Analysis:</strong> Complex texts, Shakespeare.",
        "camp.class12.p2": "<strong>Academic Writing:</strong> High-level Comment.",
        "camp.class12.p3": "<strong>Media & Politics:</strong> Evaluating global topics.",
        "camp.class12.p4": "<strong>Mediation:</strong> Communicating complex contents.",
        "camp.class13.tag": "13th Grade",
        "camp.class13.title": "Final Abitur Boost",
        "camp.class13.p1": "<strong>Discourse Analysis:</strong> Rhetorical synthesis.",
        "camp.class13.p2": "<strong>Abitur Writing:</strong> Structure under exam conditions.",
        "camp.class13.p3": "<strong>Society:</strong> Analyzing democracy and identity.",
        "camp.class13.p4": "<strong>Argumentation:</strong> Integrating counter-arguments.",
        "camp.online.btn": "Book Summer Course",

        "visa.tag": "Important Information",
        "visa.title": "Student Visa and Working Rights",
        "visa.desc": "For students planning to study in Germany, the visa process, financing, and official document preparation are of great importance.",
        "visa.item1.title": "1. Student Visa",
        "visa.item1.desc": "Usually requires an admission letter, passport, financial proof (Sperrkonto), health insurance, and academic documents.",
        "visa.item2.title": "2. Working Rights",
        "visa.item2.desc": "International students in Germany have the right to work <strong>140 full days</strong> or <strong>280 half days</strong> a year.",
        "visa.item3.title": "3. Residence Process",
        "visa.item3.desc": "The residence permit granted for educational purposes can be extended depending on the study progress.",
        "visa.item4.title": "4. Post-Graduation",
        "visa.item4.desc": "Graduates may have the opportunity to get a job-seeking visa and subsequently transition to a working residence permit.",
        "visa.warning": "<strong>Warning:</strong> The visa decision is made solely by the authorized official authorities. Preparing a complete application file is crucial.",

        "faq.title": "Frequently Asked Questions",
        "faq.q1": "1. Is university in Germany completely free?",
        "faq.a1": "There are no tuition fees at most public universities; however, semester contributions and living expenses must be planned.",
        "faq.q2": "2. Can I apply without the YKS exam?",
        "faq.a2": "This depends on the student's educational background. Every file must be evaluated individually.",
        "faq.q3": "3. Is it possible to apply without knowing German?",
        "faq.a3": "For some students, a language course, conditional admission, or preparation options can be evaluated.",
        "faq.q4": "4. Can students work in Germany?",
        "faq.a4": "Yes, within the official rules, they can work 140 full days or 280 half days a year.",
        "faq.q5": "5. Does Start Akademie guarantee admission or a visa?",
        "faq.a5": "No. The final decision is made by the respective university and official authorities.",

        "footer.desc": "Start Akademie, with its center near Frankfurt, increases school success while coordinating German public university applications of candidates from Turkey with a zero visa loss policy."
}

old_de = {
        "nav.home": "Startseite",
        "nav.programs": "Programme",
        "nav.universities": "Universitäten",
        "nav.consulting": "Beratung",
        "nav.test": "Äquivalenzprüfung",
        "nav.camp": "Sommercamp",
        "nav.contact": "Kontakt",
        "nav.meeting": "Termin Buchen",
        
        "hero.main_title": "Ihr Bildungsweg <em>in Deutschland</em>",
        "hero.seo_desc": "Ihr Premium-Zentrum für Nachhilfe und Studienzulassung in Deutschland",
        
        "hero.title": "Ihr Bildungsweg in Deutschland <em>Beginnt Hier</em>",
        "hero.subtitle": "Die Start Akademie mit Zentrum in der Nähe von Frankfurt steigert den schulischen Erfolg (Nachhilfe) von Gymnasiasten und koordiniert die Bewerbungen von Kandidaten aus der Türkei an staatlichen deutschen Universitäten mit einer Null-Visum-Verlust-Politik.",
        "hero.btn1": "Bildungsbereiche",
        "hero.btn2": "Zulassungsberatung",
        "hero.scroll": "Nach Unten Scrollen",
        
        "welcome.tag": "AKADEMISCHE BRÜCKE",
        "welcome.title": "Offizielle Zulassungs- & <em>Visaberatung</em>",
        "welcome.desc": "Riskieren Sie Ihren Bildungsweg nicht. Von der akademischen Äquivalenzanalyse bis zur Perfektionierung Ihrer offiziellen Visumsakte sichern wir alle Phasen mit unserem Fachpersonal ab.",
        "welcome.stat1": "98%",
        "welcome.stat1_desc": "ZULASSUNGSRATE",
        "welcome.stat2": "VNN",
        "welcome.stat2_desc": "AKKREDITIERTE QUALITÄT",
        
        "pillars.tag": "START PROGRAMME",
        "pillars.title": "Drei Flügel, die die Zukunft erreichen",
        "pillars.desc": "Auf Ihre Ziele zugeschnittene Bildungslösungen, von lokaler schulischer Unterstützung in Deutschland bis hin zu Studienzulassungs- und Vorbereitungskursen.",
        "pillar1.title": "Nachhilfe <em>in Deutschland</em>",
        "pillar1.tag": "Deutschsprachiger Bereich",
        "pillar1.btn": "Nachhilfe Beantragen",
        "pillar2.title": "Bildungsberatung <em>für Deutschland</em>",
        "pillar2.tag": "Kandidatenorientiert / Türkisch 🇹🇷",
        "pillar2.btn": "Zulassungsberatung Entdecken",
        "pillar3.title": "Online <em>Sprachkurse</em>",
        "pillar3.tag": "Türkisch Orientiert / Live 🇹🇷",
        "pillar3.btn": "Sprachkurs Anmelden",

        "nachhilfe.tag": "Individuelle Förderung",
        "nachhilfe.title": "Nachhilfe in Rüsselsheim",
        "nachhilfe.desc": "Wir unterstützen Ihr Kind flexibel, persönlich und zielorientiert – für bessere Noten, mehr Sicherheit und mehr Motivation im Schulalltag.",
        "nachhilfe.subjects.title": "Fächer für die Klassen 1–13",
        "nachhilfe.subjects.group1": "1. Hauptfächer",
        "nachhilfe.subjects.group2": "2. Naturwissenschaften",
        "nachhilfe.subjects.group3": "3. Weitere Fächer & Schulformen",
        "nachhilfe.subjects.group3_desc": "Geschichte, Französisch, Spanisch, Latein, DaF.<br><strong>Von der Grundschule bis zur Oberstufe.</strong>",
        "nachhilfe.models.title": "Unsere Unterrichtsmodelle",
        "nachhilfe.models.m1": "Einzelunterricht & Kleingruppen",
        "nachhilfe.models.m1_desc": "Individuelle Förderung ganz nach den Bedürfnissen Ihres Kindes.",
        "nachhilfe.models.m2": "Tandemunterricht",
        "nachhilfe.models.m2_desc": "Zwei Schüler, ein Ziel. Gemeinsam lernen, zusammen weiterkommen.",
        "nachhilfe.models.m3": "Hausaufgabenbetreuung",
        "nachhilfe.models.m3_desc": "Wir unterstützen bei Hausaufgaben und sorgen für mehr Sicherheit.",
        "nachhilfe.models.m4": "Klausur- und Prüfungsvorbereitung",
        "nachhilfe.models.m4_desc": "Gezielte Vorbereitung für Klassenarbeiten und Abschlüsse.",
        "nachhilfe.models.m5": "Online-Unterricht",
        "nachhilfe.models.m5_desc": "Flexibel lernen – auch von zu Hause aus, im Einzelunterricht.",
        
        "flat.tag": "NEU",
        "flat.title": "Hausaufgaben-Flat <span style='color: var(--gold);'>150 € / Monat</span>",
        "flat.subtitle": "Für Schülerinnen und Schüler der <strong>3.–8. Klasse</strong>. 4x pro Woche.",
        "flat.p1": "Feste Zeiten & klare Struktur",
        "flat.p2": "Kontrolle auf Richtigkeit & Vollständigkeit",
        "flat.p3": "Selbstständiges Arbeiten fördern",
        "flat.steps.title": "Ablauf der Betreuung:",
        "flat.step1": "<strong>Ankommen:</strong> Feste Zeiten zur Betreuung.",
        "flat.step2": "<strong>Selbstständig arbeiten:</strong> Hausaufgaben ruhig erledigen.",
        "flat.step3": "<strong>Unterstützung:</strong> Lehrkräfte helfen bei Fragen.",
        "flat.step4": "<strong>Kontrolle:</strong> Prüfung auf Richtigkeit.",
        "flat.step5": "<strong>Fertig?:</strong> Kind darf nach Hause gehen.",
        "flat.step6": "<strong>Keine Hausaufgaben?:</strong> Sinnvoll lernen (Lesen, Übungen).",

        "but.tag": "Bildung und Teilhabe (BuT)",
        "but.title": "Kostenlose Nachhilfe für Ihr Kind!",
        "but.desc": "Wir helfen Ihnen beim BuT-Antrag und begleiten Ihr Kind auf dem Weg zum Lernerfolg.",
        "but.who.title": "Wer kann BuT bekommen?",
        "but.who.p1": "Bürgergeld",
        "but.who.p2": "Wohngeld",
        "but.who.p3": "Kinderzuschlag",
        "but.who.p4": "Sozialhilfe / Asylbewerberleistungen",
        "but.how.title": "So beantragen Sie BuT (6 Schritte)",
        "but.how.s1": "Formular bei uns anfragen oder abholen",
        "but.how.s2": "Antrag ausfüllen",
        "but.how.s3": "Schule ergänzt die Bestätigung",
        "but.how.s4": "Unterlagen an die zuständige Stelle senden",
        "but.how.s5": "Bewilligung erhalten",
        "but.how.s6": "Mit dem Bescheid bei Start Akademie anmelden",

        "calc.tag": "SPERRKONTO RECHNER",
        "calc.title": "Sperrkonto Finanzplaner",
        "calc.desc": "Bestimmen Sie den aktuellen Sperrkonto-Betrag, den Sie für ein Bildungsvisum in Deutschland nachweisen müssen. Offizieller Referenzbetrag ist 992 €/Monat.",
        "calc.months": "Aufenthaltsdauer (Monate)",
        "calc.extra": "Monatliches Taschengeld (Optional)",
        
        "univ.tag": "STAATLICHE UNIVERSITÄTEN",
        "univ.title": "Campusse, die Ihre Zukunft prägen",
        "univ.desc": "Wir führen Ihre bedingten Zulassungsanträge an gebührenfreien staatlichen Universitäten in Deutschland durch, die weltweit hoch im Kurs stehen.",
        
        "price.tag": "PAKETE UND DIENSTLEISTUNGEN",
        "price.title": "Offizielle Beratungspakete",
        "price.desc": "Umfassende Antrags- und Visumberatungspakete nach Ihren Bedürfnissen, von der Äquivalenzanalyse bis zur Visum-Interview-Simulation.",

        "wizard.tag": "Schnelle Äquivalenzprüfung",
        "wizard.title": "Deutschland Uni-Zulassungs-Assistent",
        "wizard.desc": "Prüfen Sie in 4 Schritten schnell, ob Sie aufgrund Ihres Schulabschlusses direkt an einer deutschen staatlichen Universität zugelassen werden können.",
        "wizard.step1.q": "1. Welche Art von Schulabschluss haben Sie?",
        "wizard.step1.o1": "Anatolien- oder naturwissenschaftliches Gymnasium",
        "wizard.step1.o2": "Berufs- oder Imam-Hatip-Gymnasium",
        "wizard.step2.q": "2. Haben Sie ein internationales Diplom? (IB, Abitur, AP etc.)",
        "wizard.step2.o1": "Ja (IB / Abitur / AP vorhanden)",
        "wizard.step2.o2": "Nein (Nur YKS / High School Diploma)",
        "wizard.step3.q": "3. Wie ist Ihr aktuelles Sprachniveau in Deutsch?",
        "wizard.step3.o1": "B1 und höher",
        "wizard.step3.o2": "Anfänger / Kein",
        "wizard.step4.q": "4. Haben Sie an der YKS-Prüfung teilgenommen und einen Studienplatz erhalten?",
        "wizard.step4.o1": "Ja, in einen 4-jährigen Studiengang aufgenommen",
        "wizard.step4.o2": "Nein, noch nicht teilgenommen/aufgenommen",
        "wizard.loading": "Wird ausgewertet...",
        "wizard.btn": "Eins-zu-Eins Analysegespräch Buchen",

        "camp.tag": "Abitur & Oberstufe Boost",
        "camp.title": "Sommercamps & Intensivkurse 2026",
        "camp.desc": "Bereiten Sie sich gezielt auf die Oberstufe oder das Abitur vor – entweder intensiv vor Ort in Rüsselsheim oder flexibel im Online-Einzelunterricht.",
        "camp.inperson.tag": "Intensivcamp vor Ort",
        "camp.inperson.title": "Stark in die 12. Klasse",
        "camp.inperson.desc": "Der Übergang in die 12. Klasse ist ein entscheidender Schritt. Mit unserem Intensivcamp bereiten wir gezielt auf die Anforderungen der Oberstufe vor.",
        "camp.inperson.f1": "Mathematik Oberstufe",
        "camp.inperson.f2": "Deutsch: Analyse & Schreibtraining",
        "camp.inperson.f3": "Englisch: Essay & Textanalyse",
        "camp.inperson.f4": "Klausurtraining & Lernstrategien",
        "camp.inperson.dates": "Camp-Termine 2026",
        "camp.inperson.d1": "Samstag, 25.07.2026",
        "camp.inperson.d2": "Samstag, 01.08.2026",
        "camp.inperson.d3": "Samstag, 15.08.2026",
        "camp.inperson.d4": "Samstag, 22.08.2026",
        "camp.inperson.info1": "09:00 - 16:30 Uhr",
        "camp.inperson.info2": "5 bis max. 8 Teilnehmende",
        "camp.inperson.info3": "Start Akademie - Rüsselsheim",
        "camp.inperson.btn": "Jetzt Platz anfragen",
        "camp.online.title": "Online Sommerkurse Englisch (1:1)",
        "camp.online.desc": "4 Wochen (06.07. – 31.07.2026) | Montag bis Freitag, 90 Min. täglich | 20 Unterrichtseinheiten",
        "camp.class11.tag": "11. Klasse",
        "camp.class11.title": "Vorbereitung Oberstufe",
        "camp.class11.p1": "<strong>Grammar & Writing:</strong> Zeiten, Passiv, Essays.",
        "camp.class11.p2": "<strong>Textanalyse & Literatur:</strong> Kurzgeschichten interpretieren.",
        "camp.class11.p3": "<strong>Kultur & Medien:</strong> UK/USA Politik verstehen.",
        "camp.class11.p4": "<strong>Argumentation:</strong> Standpunkte begründen.",
        "camp.class12.tag": "12. Klasse",
        "camp.class12.title": "Qualifikationsphase",
        "camp.class12.p1": "<strong>Textanalyse:</strong> Komplexe Texte, Shakespeare.",
        "camp.class12.p2": "<strong>Academic Writing:</strong> Comment, Discussion.",
        "camp.class12.p3": "<strong>Medien & Politik:</strong> Globale Themen bewerten.",
        "camp.class12.p4": "<strong>Mediation:</strong> Inhalte souverän vermitteln.",
        "camp.class13.tag": "13. Klasse",
        "camp.class13.title": "Finaler Abitur-Boost",
        "camp.class13.p1": "<strong>Diskursanalyse:</strong> Rhetorische Analyse.",
        "camp.class13.p2": "<strong>Abitur Writing:</strong> Struktur & Präzision.",
        "camp.class13.p3": "<strong>Gesellschaft:</strong> Demokratie kritisch analysieren.",
        "camp.class13.p4": "<strong>Argumentation:</strong> Gegenargumente integrieren.",
        "camp.online.btn": "Sommerkurs Buchen",

        "visa.tag": "Wichtige Informationen",
        "visa.title": "Studentenvisum und Arbeitsrecht",
        "visa.desc": "Für Studierende, die ein Studium in Deutschland planen, sind das Visumverfahren, die Finanzierung und die Dokumentenvorbereitung von großer Bedeutung.",
        "visa.item1.title": "1. Studentenvisum",
        "visa.item1.desc": "Erfordert in der Regel eine Zulassung, Pass, Finanzierungsnachweis (Sperrkonto), Krankenversicherung und akademische Dokumente.",
        "visa.item2.title": "2. Arbeitsrecht",
        "visa.item2.desc": "Internationale Studierende haben das Recht, <strong>140 ganze Tage</strong> oder <strong>280 halbe Tage</strong> im Jahr zu arbeiten.",
        "visa.item3.title": "3. Aufenthaltsprozess",
        "visa.item3.desc": "Die zu Bildungszwecken erteilte Aufenthaltserlaubnis kann je nach Studienfortschritt verlängert werden.",
        "visa.item4.title": "4. Nach dem Abschluss",
        "visa.item4.desc": "Absolventen können eine Aufenthaltserlaubnis zur Arbeitsplatzsuche und anschließend zur Erwerbstätigkeit erhalten.",
        "visa.warning": "<strong>Warnung:</strong> Die Visumentscheidung wird ausschließlich von den befugten Behörden getroffen. Eine vollständige Antragsakte ist entscheidend.",

        "faq.title": "Häufig Gestellte Fragen",
        "faq.q1": "1. Ist das Studium in Deutschland komplett kostenlos?",
        "faq.a1": "An den meisten staatlichen Universitäten gibt es keine Studiengebühren; Semesterbeiträge und Lebenshaltungskosten müssen jedoch eingeplant werden.",
        "faq.q2": "2. Kann ich mich ohne die YKS-Prüfung bewerben?",
        "faq.a2": "Dies hängt vom schulischen Hintergrund des Schülers ab. Jede Akte muss individuell bewertet werden.",
        "faq.q3": "3. Ist eine Bewerbung ohne Deutschkenntnisse möglich?",
        "faq.a3": "Für einige Schüler können ein Sprachkurs, eine bedingte Zulassung oder Vorbereitungsoptionen geprüft werden.",
        "faq.q4": "4. Dürfen Studenten in Deutschland arbeiten?",
        "faq.a4": "Ja, im Rahmen der offiziellen Regeln dürfen sie 140 ganze oder 280 halbe Tage im Jahr arbeiten.",
        "faq.q5": "5. Garantiert Start Akademie die Zulassung oder ein Visum?",
        "faq.a5": "Nein. Die endgültige Entscheidung wird von der jeweiligen Universität und den offiziellen Behörden getroffen.",

        "footer.desc": "Die Start Akademie mit Zentrum in der Nähe von Frankfurt steigert den schulischen Erfolg und koordiniert die Bewerbungen von Kandidaten aus der Türkei an staatlichen Universitäten mit einer Null-Visum-Verlust-Politik."
}

# Add new translations
new_translations = {
    'tr': {}, 'en': {}, 'de': {}
}

# I will just write the replacement script code in the same python script

new_translations = {
    'tr': {
        "pillar1.f1": "Grundschule, Mittel- und Oberstufe",
        "pillar1.f2": "Tüm yaygın okul derslerinde özel destek",
        "pillar1.f3": "Birebir ve odaklanmış küçük gruplar",
        "pillar1.f4": "BuT devlet yardımı ile tamamen ücretsiz",
        "pillar2.f1": "Almanya'da Lisans ve Yüksek Lisans",
        "pillar2.f2": "Ausbildung (Mesleki Eğitim) yerleşimi",
        "pillar2.f3": "Akademik uygunluk ve vize dosyası",
        "pillar2.f4": "Kişisel dosya rehberliği & danışmanlık",
        "pillar3.f1": "Online Deutschkurse (A1 - C1)",
        "pillar3.f2": "Online Englischkurse (A1 - C1)",
        "pillar3.f3": "Nitelikli eğitim kadrosuyla canlı ders",
        "pillar3.f4": "Türkiye'den esnek saatli katılım modeli",
        
        "calc.labels.duration": "Kalınacak Süre (Ay)",
        "calc.labels.extra": "Aylık Ek Harçlık (Opsiyonel)",
        "calc.val.12months": "12 Ay",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Finansal Oran Dağılımı",
        "calc.res.legend1": "Resmi Bloke Hesap",
        "calc.res.legend2": "İşlem Ücreti",
        "calc.res.totalTitle": "Toplam Gerekli Bütçe",
        "calc.res.monthly": "Aylık Bloke Ödeme:",
        "calc.res.monthlyVal": "992 € / Ay",
        "calc.res.total": "Toplam Bloke Tutar:",
        "calc.res.totalVal": "11.904 €",
        "calc.res.fee": "Kurulum ve İşlem Harcı:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Kabul: ~%15",
        "univ.title.heidelberg": "Heidelberg Üniversitesi",
        "univ.desc.heidelberg": "1386 kuruluş yılıyla Almanya'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.",
        "univ.tag.munich": "📍 MÜNİH",
        "univ.rate.munich": "Kabul: ~%8",
        "univ.title.munich": "Münih Teknik Üniversitesi (TUM)",
        "univ.desc.munich": "Avrupa'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Kabul: ~%20",
        "univ.title.frankfurt": "Goethe Üniversitesi",
        "univ.desc.frankfurt": "Frankfurt'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Temel Başvuru Paketi",
        "price.basic.f1": "Akademik Uygunluk Analizi",
        "price.basic.f2": "Bölüm ve Üniversite Seçimi",
        "price.basic.f3": "3 Üniversiteye Kadar Başvuru",
        "price.basic.f4": "Temel Motivasyon Mektubu Desteği",
        "price.basic.f5": "Vize Görüşmesi Simülasyonu",
        "price.basic.f6": "Almanya Sonrası Destek",
        "price.basic.btn": "Basic Paket Seç",
        "price.plus.badge": "En Çok Tercih Edilen",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Kapsamlı Başvuru & Kabul",
        "price.plus.f1": "Akademik Uygunluk Analizi",
        "price.plus.f2": "5 Üniversiteye Kadar Başvuru",
        "price.plus.f3": "Detaylı Motivasyon & CV Tasarımı",
        "price.plus.f4": "Detaylı Vize Evrak Dosyası Hazırlığı",
        "price.plus.f5": "1 Adet Vize Randevu Simülasyonu",
        "price.plus.f6": "Almanya Sonrası 3 Ay Destek",
        "price.plus.btn": "Plus Paket Seç",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Vize & Varış Garantili VIP",
        "price.premium.f1": "Akademik Uygunluk Analizi",
        "price.premium.f2": "8 Üniversiteye Kadar Başvuru",
        "price.premium.f3": "Genişletilmiş CV & Motivasyon Yazımı",
        "price.premium.f4": "2 Adet Birebir Vize Simülasyonu",
        "price.premium.f5": "Detaylı Konaklama & Yurt Yönlendirmesi",
        "price.premium.f6": "Almanya Sonrası 6 Ay Destek",
        "price.premium.btn": "Premium Paket Seç",
        "price.extra.title": "Ek Hizmetler",
        "price.extra.f1": "Vize Rehberim Paketi",
        "price.extra.f2": "Tek Başvuru Üniversite Paketi",
        "price.extra.f3": "Almanya'ya Varış ve İlk Adımlar",
        "price.extra.f4": "Almanca Hazırlık ve Dil Planlama",
        "price.extra.note": "Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.",
        
        "contact.tag": "Kurumsal İrtibat",
        "contact.title": "Başvurunuzu Planlayın",
        "contact.desc": "Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.",
        "contact.address.title": "Start Akademie UG Merkez Adresi",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Telefon / WhatsApp İrtibat",
        "contact.phone.desc": "0179 7424790",
        "contact.email.title": "Resmi E-Posta",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Kişiselleştirilmiş Randevu Alın",
        "contact.form.desc": "Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.",
        "contact.form.l_name": "Adınız Soyadınız",
        "contact.form.l_phone": "Telefon / WhatsApp",
        "contact.form.l_email": "E-Posta Adresiniz",
        "contact.form.l_service": "Hizmet Alanı",
        "contact.form.l_date": "Görüşme Tarihi",
        "contact.form.btn": "Görüşme Talebi Gönder",
        "contact.bot.title": "StartBotAsistanı",
        "contact.bot.b1": "Bloke Hesap Miktarı",
        "contact.bot.b2": "Ücretsiz BuT Desteği",
        "contact.bot.b3": "Adres & İletişim",
        "contact.form.p_name": "Adınız Soyadınız",
        "contact.form.p_phone": "05XX XXX XX XX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Sorunuzu buraya yazın...",
        
        "footer.services.title": "Hizmetler",
        "footer.services.l1": "Okul Ders Desteği (Nachhilfe)",
        "footer.services.l2": "Üniversite Danışmanlığı",
        "footer.services.l3": "Online Almanca Kursları",
        "footer.services.l4": "Yaz Dil Kampları 2026",
        "footer.corporate.title": "Kurumsal",
        "footer.corporate.l1": "Genel Müdür: Mevlüt Uysal",
        "footer.corporate.l2": "Etüt Merkezi: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Adresi: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Yasal Bilgiler",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau Lisansı",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.",
        "footer.privacy": "Gizlilik Sözleşmesi",
        "footer.terms": "Kullanım Koşulları"
    },
    'en': {
        "pillar1.f1": "Primary, Middle and High School",
        "pillar1.f2": "Special support in all common school subjects",
        "pillar1.f3": "One-on-one and focused small groups",
        "pillar1.f4": "Completely free with BuT government aid",
        "pillar2.f1": "Bachelor's and Master's in Germany",
        "pillar2.f2": "Ausbildung (Vocational Training) placement",
        "pillar2.f3": "Academic eligibility and visa file",
        "pillar2.f4": "Personal file guidance & consulting",
        "pillar3.f1": "Online German Courses (A1 - C1)",
        "pillar3.f2": "Online English Courses (A1 - C1)",
        "pillar3.f3": "Live classes with qualified teaching staff",
        "pillar3.f4": "Flexible attendance model from Turkey",
        
        "calc.labels.duration": "Duration of Stay (Months)",
        "calc.labels.extra": "Monthly Extra Pocket Money (Optional)",
        "calc.val.12months": "12 Months",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Financial Ratio Breakdown",
        "calc.res.legend1": "Official Blocked Account",
        "calc.res.legend2": "Processing Fee",
        "calc.res.totalTitle": "Total Required Budget",
        "calc.res.monthly": "Monthly Blocked Payment:",
        "calc.res.monthlyVal": "992 € / Month",
        "calc.res.total": "Total Blocked Amount:",
        "calc.res.totalVal": "11,904 €",
        "calc.res.fee": "Setup and Processing Fee:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Acceptance: ~15%",
        "univ.title.heidelberg": "Heidelberg University",
        "univ.desc.heidelberg": "Founded in 1386, Germany's oldest and most prestigious university. A global leader in medicine, pharmacy, and natural sciences.",
        "univ.tag.munich": "📍 MUNICH",
        "univ.rate.munich": "Acceptance: ~8%",
        "univ.title.munich": "Technical University of Munich (TUM)",
        "univ.desc.munich": "Europe's technology hub. Ranks among the world's best universities in engineering, computer science, and artificial intelligence.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Acceptance: ~20%",
        "univ.title.frankfurt": "Goethe University",
        "univ.desc.frankfurt": "A leading global research university in the heart of Frankfurt, excelling in economics, finance, social sciences, and humanities.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Basic Application Package",
        "price.basic.f1": "Academic Eligibility Analysis",
        "price.basic.f2": "Department and University Selection",
        "price.basic.f3": "Application to Up to 3 Universities",
        "price.basic.f4": "Basic Motivation Letter Support",
        "price.basic.f5": "Visa Interview Simulation",
        "price.basic.f6": "Post-Germany Support",
        "price.basic.btn": "Choose Basic Package",
        "price.plus.badge": "Most Preferred",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Comprehensive App & Admission",
        "price.plus.f1": "Academic Eligibility Analysis",
        "price.plus.f2": "Application to Up to 5 Universities",
        "price.plus.f3": "Detailed Motivation & CV Design",
        "price.plus.f4": "Detailed Visa Document Prep",
        "price.plus.f5": "1 Visa Appointment Simulation",
        "price.plus.f6": "3 Months Post-Germany Support",
        "price.plus.btn": "Choose Plus Package",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Visa & Arrival Guaranteed VIP",
        "price.premium.f1": "Academic Eligibility Analysis",
        "price.premium.f2": "Application to Up to 8 Universities",
        "price.premium.f3": "Extended CV & Motivation Writing",
        "price.premium.f4": "2 One-on-One Visa Simulations",
        "price.premium.f5": "Detailed Housing & Dorm Guidance",
        "price.premium.f6": "6 Months Post-Germany Support",
        "price.premium.btn": "Choose Premium Package",
        "price.extra.title": "Additional Services",
        "price.extra.f1": "My Visa Guide Package",
        "price.extra.f2": "Single Application University Package",
        "price.extra.f3": "Arrival in Germany and First Steps",
        "price.extra.f4": "German Prep and Language Planning",
        "price.extra.note": "Additional university / program applications may be charged extra.",
        
        "contact.tag": "Corporate Contact",
        "contact.title": "Plan Your Application",
        "contact.desc": "Evaluate your visa & equivalence documents with our expert guides by registering at our education office near Frankfurt or for an online appointment.",
        "contact.address.title": "Start Akademie UG Head Office",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Phone / WhatsApp Contact",
        "contact.phone.desc": "+49 179 7424790",
        "contact.email.title": "Official Email",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Get a Personalized Appointment",
        "contact.form.desc": "Please fill out your information completely. Our education consultants will get back to you within 24 hours.",
        "contact.form.l_name": "Full Name",
        "contact.form.l_phone": "Phone / WhatsApp",
        "contact.form.l_email": "Your Email Address",
        "contact.form.l_service": "Service Area",
        "contact.form.l_date": "Meeting Date",
        "contact.form.btn": "Send Meeting Request",
        "contact.bot.title": "StartBotAssistant",
        "contact.bot.b1": "Blocked Account Amount",
        "contact.bot.b2": "Free BuT Support",
        "contact.bot.b3": "Address & Contact",
        "contact.form.p_name": "Full Name",
        "contact.form.p_phone": "+90 5XX XXX XX XX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Write your question here...",
        
        "footer.services.title": "Services",
        "footer.services.l1": "School Tutoring (Nachhilfe)",
        "footer.services.l2": "University Consulting",
        "footer.services.l3": "Online German Courses",
        "footer.services.l4": "Summer Language Camps 2026",
        "footer.corporate.title": "Corporate",
        "footer.corporate.l1": "General Manager: Mevlüt Uysal",
        "footer.corporate.l2": "Study Center: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Address: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Legal Information",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau License",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). All rights reserved.",
        "footer.privacy": "Privacy Policy",
        "footer.terms": "Terms of Use"
    },
    'de': {
        "pillar1.f1": "Grundschule, Mittel- und Oberstufe",
        "pillar1.f2": "Spezielle Unterstützung in allen gängigen Schulfächern",
        "pillar1.f3": "Einzelunterricht und fokussierte Kleingruppen",
        "pillar1.f4": "Komplett kostenlos mit BuT-Staatshilfe",
        "pillar2.f1": "Bachelor und Master in Deutschland",
        "pillar2.f2": "Ausbildungsvermittlung",
        "pillar2.f3": "Akademische Eignung und Visumsakte",
        "pillar2.f4": "Persönliche Aktenführung & Beratung",
        "pillar3.f1": "Online Deutschkurse (A1 - C1)",
        "pillar3.f2": "Online Englischkurse (A1 - C1)",
        "pillar3.f3": "Live-Unterricht mit qualifiziertem Lehrpersonal",
        "pillar3.f4": "Flexibles Teilnahmemodell aus der Türkei",
        
        "calc.labels.duration": "Aufenthaltsdauer (Monate)",
        "calc.labels.extra": "Monatliches Taschengeld (Optional)",
        "calc.val.12months": "12 Monate",
        "calc.val.0eur": "0 €",
        "calc.res.title": "Finanzielle Aufteilung",
        "calc.res.legend1": "Offizielles Sperrkonto",
        "calc.res.legend2": "Bearbeitungsgebühr",
        "calc.res.totalTitle": "Gesamtes Benötigtes Budget",
        "calc.res.monthly": "Monatliche Sperrzahlung:",
        "calc.res.monthlyVal": "992 € / Monat",
        "calc.res.total": "Gesamter Sperrbetrag:",
        "calc.res.totalVal": "11.904 €",
        "calc.res.fee": "Einrichtungs- und Bearbeitungsgebühr:",
        "calc.res.feeVal": "99 €",
        
        "univ.tag.heidelberg": "📍 HEIDELBERG",
        "univ.rate.heidelberg": "Zulassung: ~15%",
        "univ.title.heidelberg": "Universität Heidelberg",
        "univ.desc.heidelberg": "Gegründet 1386, Deutschlands älteste und renommierteste Universität. Weltweit führend in Medizin, Pharmazie und Naturwissenschaften.",
        "univ.tag.munich": "📍 MÜNCHEN",
        "univ.rate.munich": "Zulassung: ~8%",
        "univ.title.munich": "Technische Universität München (TUM)",
        "univ.desc.munich": "Europas Technologie-Hub. Zählt zu den weltbesten Universitäten in Ingenieurwesen, Informatik und Künstlicher Intelligenz.",
        "univ.tag.frankfurt": "📍 FRANKFURT",
        "univ.rate.frankfurt": "Zulassung: ~20%",
        "univ.title.frankfurt": "Goethe-Universität",
        "univ.desc.frankfurt": "Führende globale Forschungsuniversität im Herzen von Frankfurt, exzellent in Wirtschaft, Finanzen, Sozial- und Geisteswissenschaften.",
        
        "price.basic.tag": "START BASIC",
        "price.basic.title": "Basis-Bewerbungspaket",
        "price.basic.f1": "Akademische Eignungsanalyse",
        "price.basic.f2": "Fach- und Universitätsauswahl",
        "price.basic.f3": "Bewerbung an bis zu 3 Universitäten",
        "price.basic.f4": "Unterstützung beim Basis-Motivationsschreiben",
        "price.basic.f5": "Simulation des Visuminterviews",
        "price.basic.f6": "Betreuung nach Ankunft in Deutschland",
        "price.basic.btn": "Basis-Paket Wählen",
        "price.plus.badge": "Am Beliebtesten",
        "price.plus.tag": "START PLUS",
        "price.plus.title": "Umfassende Bewerbung & Zulassung",
        "price.plus.f1": "Akademische Eignungsanalyse",
        "price.plus.f2": "Bewerbung an bis zu 5 Universitäten",
        "price.plus.f3": "Detaillierte Motivations- & Lebenslaufgestaltung",
        "price.plus.f4": "Detaillierte Vorbereitung der Visumsdokumente",
        "price.plus.f5": "1 Visumtermin-Simulation",
        "price.plus.f6": "3 Monate Betreuung nach Ankunft",
        "price.plus.btn": "Plus-Paket Wählen",
        "price.premium.tag": "START PREMIUM",
        "price.premium.title": "Visum & Ankunft Garantiert VIP",
        "price.premium.f1": "Akademische Eignungsanalyse",
        "price.premium.f2": "Bewerbung an bis zu 8 Universitäten",
        "price.premium.f3": "Erweitertes Schreiben von Lebenslauf & Motivation",
        "price.premium.f4": "2 Einzel-Visumsimulationen",
        "price.premium.f5": "Detaillierte Wohnungs- & Wohnheimvermittlung",
        "price.premium.f6": "6 Monate Betreuung nach Ankunft",
        "price.premium.btn": "Premium-Paket Wählen",
        "price.extra.title": "Zusätzliche Dienstleistungen",
        "price.extra.f1": "Mein Visum-Guide Paket",
        "price.extra.f2": "Einzelbewerbung Universitäts-Paket",
        "price.extra.f3": "Ankunft in Deutschland und erste Schritte",
        "price.extra.f4": "Deutschvorbereitung und Sprachplanung",
        "price.extra.note": "Zusätzliche Universitäts- / Programmbewerbungen können extra berechnet werden.",
        
        "contact.tag": "Unternehmenskontakt",
        "contact.title": "Planen Sie Ihre Bewerbung",
        "contact.desc": "Bewerten Sie Ihre Visum- & Äquivalenzdokumente mit unseren Fachberatern, indem Sie sich in unserem Bildungsbüro nahe Frankfurt oder für einen Online-Termin registrieren.",
        "contact.address.title": "Start Akademie UG Hauptsitz",
        "contact.address.desc": "Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main",
        "contact.phone.title": "Telefon / WhatsApp Kontakt",
        "contact.phone.desc": "+49 179 7424790",
        "contact.email.title": "Offizielle E-Mail",
        "contact.email.desc": "info@startakademie.de",
        "contact.form.title": "Holen Sie sich einen persönlichen Termin",
        "contact.form.desc": "Bitte füllen Sie Ihre Daten vollständig aus. Unsere Bildungsberater werden sich innerhalb von 24 Stunden bei Ihnen melden.",
        "contact.form.l_name": "Vollständiger Name",
        "contact.form.l_phone": "Telefon / WhatsApp",
        "contact.form.l_email": "Ihre E-Mail-Adresse",
        "contact.form.l_service": "Servicebereich",
        "contact.form.l_date": "Termindatum",
        "contact.form.btn": "Terminanfrage Senden",
        "contact.bot.title": "StartBotAssistent",
        "contact.bot.b1": "Sperrkonto-Betrag",
        "contact.bot.b2": "Kostenlose BuT-Unterstützung",
        "contact.bot.b3": "Adresse & Kontakt",
        "contact.form.p_name": "Vollständiger Name",
        "contact.form.p_phone": "+49 1XX XXXXXXX",
        "contact.form.p_email": "mail@example.com",
        "contact.form.p_msg": "Schreiben Sie hier Ihre Frage...",
        
        "footer.services.title": "Dienstleistungen",
        "footer.services.l1": "Schulnachhilfe",
        "footer.services.l2": "Universitätsberatung",
        "footer.services.l3": "Online Deutschkurse",
        "footer.services.l4": "Sommer-Sprachcamps 2026",
        "footer.corporate.title": "Unternehmen",
        "footer.corporate.l1": "Geschäftsführer: Mevlüt Uysal",
        "footer.corporate.l2": "Studienzentrum: Bahnhofstraße 22",
        "footer.corporate.l3": "UG Adresse: Bahnhofstraße 22 / 22a",
        "footer.corporate.l4": "Instagram: @startakademie",
        "footer.legal.title": "Rechtliche Informationen",
        "footer.legal.l1": "Impressum",
        "footer.legal.l2": "Datenschutzerklärung",
        "footer.legal.l3": "Anerkannter Lernförderanbieter",
        "footer.legal.l4": "Kreis Groß-Gerau Lizenz",
        "footer.copy": "© 2026 Start Akademie UG (haftungsbeschränkt). Alle Rechte vorbehalten.",
        "footer.privacy": "Datenschutzvertrag",
        "footer.terms": "Nutzungsbedingungen"
    }
}

old_tr.update(new_translations['tr'])
old_en.update(new_translations['en'])
old_de.update(new_translations['de'])

merged = {
    'tr': old_tr,
    'en': old_en,
    'de': old_de
}

new_js = "const translations = " + json.dumps(merged, indent=4, ensure_ascii=False) + ";"
with codecs.open('assets/lang.js', 'w', encoding='utf-8') as f:
    f.write(new_js)

# HTML Replacements mapping literal strings to their new keys
html_replacements = {
    # Pills
    '<li>Grundschule, Mittel- und Oberstufe</li>': '<li data-i18n="pillar1.f1">Grundschule, Mittel- und Oberstufe</li>',
    '<li>Tüm yaygın okul derslerinde özel destek</li>': '<li data-i18n="pillar1.f2">Tüm yaygın okul derslerinde özel destek</li>',
    '<li>Birebir ve odaklanmış küçük gruplar</li>': '<li data-i18n="pillar1.f3">Birebir ve odaklanmış küçük gruplar</li>',
    '<li>BuT devlet yardımı ile tamamen ücretsiz</li>': '<li data-i18n="pillar1.f4">BuT devlet yardımı ile tamamen ücretsiz</li>',
    "<li>Almanya'da Lisans ve Yüksek Lisans</li>": '<li data-i18n="pillar2.f1">Almanya\'da Lisans ve Yüksek Lisans</li>',
    '<li>Ausbildung (Mesleki Eğitim) yerleşimi</li>': '<li data-i18n="pillar2.f2">Ausbildung (Mesleki Eğitim) yerleşimi</li>',
    '<li>Akademik uygunluk ve vize dosyası</li>': '<li data-i18n="pillar2.f3">Akademik uygunluk ve vize dosyası</li>',
    '<li>Kişisel dosya rehberliği & danışmanlık</li>': '<li data-i18n="pillar2.f4">Kişisel dosya rehberliği & danışmanlık</li>',
    '<li>Online Deutschkurse (A1 - C1)</li>': '<li data-i18n="pillar3.f1">Online Deutschkurse (A1 - C1)</li>',
    '<li>Online Englischkurse (A1 - C1)</li>': '<li data-i18n="pillar3.f2">Online Englischkurse (A1 - C1)</li>',
    '<li>Nitelikli eğitim kadrosuyla canlı ders</li>': '<li data-i18n="pillar3.f3">Nitelikli eğitim kadrosuyla canlı ders</li>',
    "<li>Türkiye'den esnek saatli katılım modeli</li>": '<li data-i18n="pillar3.f4">Türkiye\'den esnek saatli katılım modeli</li>',
    
    # Calc
    '<span style="font-weight: 600;">Kalınacak Süre (Ay)</span>': '<span style="font-weight: 600;" data-i18n="calc.labels.duration">Kalınacak Süre (Ay)</span>',
    '<span style="font-weight: 600;">Aylık Ek Harçlık (Opsiyonel)</span>': '<span style="font-weight: 600;" data-i18n="calc.labels.extra">Aylık Ek Harçlık (Opsiyonel)</span>',
    '<span id="duration-val" style="color: var(--primary);">12 Ay</span>': '<span id="duration-val" style="color: var(--primary);" data-i18n="calc.val.12months">12 Ay</span>',
    '<span id="extra-val" style="color: var(--primary);">0 €</span>': '<span id="extra-val" style="color: var(--primary);" data-i18n="calc.val.0eur">0 €</span>',
    '<span style="font-size: 0.95rem; font-weight: 600; color: var(--text-muted); letter-spacing: 1px; text-transform: uppercase;">Finansal Oran Dağılımı</span>': '<span style="font-size: 0.95rem; font-weight: 600; color: var(--text-muted); letter-spacing: 1px; text-transform: uppercase;" data-i18n="calc.res.title">Finansal Oran Dağılımı</span>',
    '<span style="font-size: 0.85rem; color: var(--text-muted);">Resmi Bloke Hesap</span>': '<span style="font-size: 0.85rem; color: var(--text-muted);" data-i18n="calc.res.legend1">Resmi Bloke Hesap</span>',
    '<span style="font-size: 0.85rem; color: var(--text-muted);">İşlem Ücreti</span>': '<span style="font-size: 0.85rem; color: var(--text-muted);" data-i18n="calc.res.legend2">İşlem Ücreti</span>',
    '<span style="font-size: 1.1rem; color: var(--text-muted);">Toplam Gerekli Bütçe</span>': '<span style="font-size: 1.1rem; color: var(--text-muted);" data-i18n="calc.res.totalTitle">Toplam Gerekli Bütçe</span>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Aylık Bloke Ödeme:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.monthly">Aylık Bloke Ödeme:</span>',
    '<strong id="monthly-amount" style="font-size: 1.2rem; color: var(--primary);">992 € / Ay</strong>': '<strong id="monthly-amount" style="font-size: 1.2rem; color: var(--primary);" data-i18n="calc.res.monthlyVal">992 € / Ay</strong>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Toplam Bloke Tutar:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.total">Toplam Bloke Tutar:</span>',
    '<strong id="total-blocked" style="font-size: 1.2rem; color: var(--text);">11.904 €</strong>': '<strong id="total-blocked" style="font-size: 1.2rem; color: var(--text);" data-i18n="calc.res.totalVal">11.904 €</strong>',
    '<span style="font-size: 0.9rem; color: var(--text-muted);">Kurulum ve İşlem Harcı:</span>': '<span style="font-size: 0.9rem; color: var(--text-muted);" data-i18n="calc.res.fee">Kurulum ve İşlem Harcı:</span>',
    '<strong style="font-size: 1.2rem; color: var(--text);">99 €</strong>': '<strong style="font-size: 1.2rem; color: var(--text);" data-i18n="calc.res.feeVal">99 €</strong>',

    # Univ
    '<span class="univ-tag">📍 HEIDELBERG</span>': '<span class="univ-tag" data-i18n="univ.tag.heidelberg">📍 HEIDELBERG</span>',
    '<span class="univ-rate">Kabul: ~%15</span>': '<span class="univ-rate" data-i18n="univ.rate.heidelberg">Kabul: ~%15</span>',
    '<h3>Heidelberg Üniversitesi</h3>': '<h3 data-i18n="univ.title.heidelberg">Heidelberg Üniversitesi</h3>',
    '<p>1386 kuruluş yılıyla Almanya\'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.</p>': '<p data-i18n="univ.desc.heidelberg">1386 kuruluş yılıyla Almanya\'nın en eski ve en prestijli üniversitesi. Tıp, eczacılık ve doğa bilimlerinde dünya çapında liderdir.</p>',
    '<span class="univ-tag">📍 MÜNİH</span>': '<span class="univ-tag" data-i18n="univ.tag.munich">📍 MÜNİH</span>',
    '<span class="univ-rate">Kabul: ~%8</span>': '<span class="univ-rate" data-i18n="univ.rate.munich">Kabul: ~%8</span>',
    '<h3>Münih Teknik Üniversitesi (TUM)</h3>': '<h3 data-i18n="univ.title.munich">Münih Teknik Üniversitesi (TUM)</h3>',
    '<p>Avrupa\'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.</p>': '<p data-i18n="univ.desc.munich">Avrupa\'nın teknoloji üssü. Mühendislik, bilgisayar bilimi ve yapay zekada dünyanın en iyi üniversiteleri arasında yer alır.</p>',
    '<span class="univ-tag">📍 FRANKFURT</span>': '<span class="univ-tag" data-i18n="univ.tag.frankfurt">📍 FRANKFURT</span>',
    '<span class="univ-rate">Kabul: ~%20</span>': '<span class="univ-rate" data-i18n="univ.rate.frankfurt">Kabul: ~%20</span>',
    '<h3>Goethe Üniversitesi</h3>': '<h3 data-i18n="univ.title.frankfurt">Goethe Üniversitesi</h3>',
    '<p>Frankfurt\'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.</p>': '<p data-i18n="univ.desc.frankfurt">Frankfurt\'un merkezinde ekonomi, finans, sosyal bilimler ve beşeri bilimlerde öncü küresel araştırma üniversitesi.</p>',

    # Pricing
    '<h3>START BASIC</h3>': '<h3 data-i18n="price.basic.tag">START BASIC</h3>',
    '<p>Temel Başvuru Paketi</p>': '<p data-i18n="price.basic.title">Temel Başvuru Paketi</p>',
    '<li>Akademik Uygunluk Analizi</li>': '<li data-i18n="price.basic.f1">Akademik Uygunluk Analizi</li>',
    '<li>Bölüm ve Üniversite Seçimi</li>': '<li data-i18n="price.basic.f2">Bölüm ve Üniversite Seçimi</li>',
    '<li>3 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.basic.f3">3 Üniversiteye Kadar Başvuru</li>',
    '<li>Temel Motivasyon Mektubu Desteği</li>': '<li data-i18n="price.basic.f4">Temel Motivasyon Mektubu Desteği</li>',
    '<li>Vize Görüşmesi Simülasyonu</li>': '<li data-i18n="price.basic.f5">Vize Görüşmesi Simülasyonu</li>',
    '<li>Almanya Sonrası Destek</li>': '<li data-i18n="price.basic.f6">Almanya Sonrası Destek</li>',
    '<a href="#contact" class="btn btn-outline">Basic Paket Seç</a>': '<a href="#contact" class="btn btn-outline" data-i18n="price.basic.btn">Basic Paket Seç</a>',
    
    '<span class="badge">En Çok Tercih Edilen</span>': '<span class="badge" data-i18n="price.plus.badge">En Çok Tercih Edilen</span>',
    '<h3>START PLUS</h3>': '<h3 data-i18n="price.plus.tag">START PLUS</h3>',
    '<p>Kapsamlı Başvuru & Kabul</p>': '<p data-i18n="price.plus.title">Kapsamlı Başvuru & Kabul</p>',
    '<li>5 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.plus.f2">5 Üniversiteye Kadar Başvuru</li>',
    '<li>Detaylı Motivasyon & CV Tasarımı</li>': '<li data-i18n="price.plus.f3">Detaylı Motivasyon & CV Tasarımı</li>',
    '<li>Detaylı Vize Evrak Dosyası Hazırlığı</li>': '<li data-i18n="price.plus.f4">Detaylı Vize Evrak Dosyası Hazırlığı</li>',
    '<li>1 Adet Vize Randevu Simülasyonu</li>': '<li data-i18n="price.plus.f5">1 Adet Vize Randevu Simülasyonu</li>',
    '<li>Almanya Sonrası 3 Ay Destek</li>': '<li data-i18n="price.plus.f6">Almanya Sonrası 3 Ay Destek</li>',
    '<a href="#contact" class="btn btn-primary">Plus Paket Seç</a>': '<a href="#contact" class="btn btn-primary" data-i18n="price.plus.btn">Plus Paket Seç</a>',

    '<h3>START PREMIUM</h3>': '<h3 data-i18n="price.premium.tag">START PREMIUM</h3>',
    '<p>Vize & Varış Garantili VIP</p>': '<p data-i18n="price.premium.title">Vize & Varış Garantili VIP</p>',
    '<li>8 Üniversiteye Kadar Başvuru</li>': '<li data-i18n="price.premium.f2">8 Üniversiteye Kadar Başvuru</li>',
    '<li>Genişletilmiş CV & Motivasyon Yazımı</li>': '<li data-i18n="price.premium.f3">Genişletilmiş CV & Motivasyon Yazımı</li>',
    '<li>2 Adet Birebir Vize Simülasyonu</li>': '<li data-i18n="price.premium.f4">2 Adet Birebir Vize Simülasyonu</li>',
    '<li>Detaylı Konaklama & Yurt Yönlendirmesi</li>': '<li data-i18n="price.premium.f5">Detaylı Konaklama & Yurt Yönlendirmesi</li>',
    '<li>Almanya Sonrası 6 Ay Destek</li>': '<li data-i18n="price.premium.f6">Almanya Sonrası 6 Ay Destek</li>',
    '<a href="#contact" class="btn btn-outline">Premium Paket Seç</a>': '<a href="#contact" class="btn btn-outline" data-i18n="price.premium.btn">Premium Paket Seç</a>',

    '<h3>Ek Hizmetler</h3>': '<h3 data-i18n="price.extra.title">Ek Hizmetler</h3>',
    '<h4>Vize Rehberim Paketi</h4>': '<h4 data-i18n="price.extra.f1">Vize Rehberim Paketi</h4>',
    '<h4>Tek Başvuru Üniversite Paketi</h4>': '<h4 data-i18n="price.extra.f2">Tek Başvuru Üniversite Paketi</h4>',
    '<h4>Almanya\'ya Varış ve İlk Adımlar</h4>': '<h4 data-i18n="price.extra.f3">Almanya\'ya Varış ve İlk Adımlar</h4>',
    '<h4>Almanca Hazırlık ve Dil Planlama</h4>': '<h4 data-i18n="price.extra.f4">Almanca Hazırlık ve Dil Planlama</h4>',
    '<p>Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.</p>': '<p data-i18n="price.extra.note">Ek üniversite / program başvuruları ayrıca ücretlendirilebilir.</p>',

    # Contact
    '<span class="section-tag">Kurumsal İrtibat</span>': '<span class="section-tag" data-i18n="contact.tag">Kurumsal İrtibat</span>',
    '<h2>Başvurunuzu Planlayın</h2>': '<h2 data-i18n="contact.title">Başvurunuzu Planlayın</h2>',
    '<p>Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.</p>': '<p data-i18n="contact.desc">Frankfurt yakınlarındaki eğitim ofisimize veya online randevuya kaydolarak vize & denklik evraklarınızı uzman rehberlerimizle değerlendirin.</p>',
    '<h4>Start Akademie UG Merkez Adresi</h4>': '<h4 data-i18n="contact.address.title">Start Akademie UG Merkez Adresi</h4>',
    '<p>Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main</p>': '<p data-i18n="contact.address.desc">Bahnhofstraße 22 / 22a, 65428 Rüsselsheim am Main</p>',
    '<h4>Telefon / WhatsApp İrtibat</h4>': '<h4 data-i18n="contact.phone.title">Telefon / WhatsApp İrtibat</h4>',
    '<p>0179 7424790</p>': '<p data-i18n="contact.phone.desc">0179 7424790</p>',
    '<h4>Resmi E-Posta</h4>': '<h4 data-i18n="contact.email.title">Resmi E-Posta</h4>',
    '<p>info@startakademie.de</p>': '<p data-i18n="contact.email.desc">info@startakademie.de</p>',
    
    '<h3>Kişiselleştirilmiş Randevu Alın</h3>': '<h3 data-i18n="contact.form.title">Kişiselleştirilmiş Randevu Alın</h3>',
    '<p>Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.</p>': '<p data-i18n="contact.form.desc">Lütfen bilgilerinizi eksiksiz doldurun. Eğitim danışmanlarımız 24 saat içinde size dönüş yapacaktır.</p>',
    '<label>Adınız Soyadınız</label>': '<label data-i18n="contact.form.l_name">Adınız Soyadınız</label>',
    'placeholder="Adınız Soyadınız"': 'placeholder="Adınız Soyadınız" data-i18n-placeholder="contact.form.p_name"',
    '<label>Telefon / WhatsApp</label>': '<label data-i18n="contact.form.l_phone">Telefon / WhatsApp</label>',
    'placeholder="05XX XXX XX XX"': 'placeholder="05XX XXX XX XX" data-i18n-placeholder="contact.form.p_phone"',
    '<label>E-Posta Adresiniz</label>': '<label data-i18n="contact.form.l_email">E-Posta Adresiniz</label>',
    'placeholder="mail@example.com"': 'placeholder="mail@example.com" data-i18n-placeholder="contact.form.p_email"',
    '<label>Hizmet Alanı</label>': '<label data-i18n="contact.form.l_service">Hizmet Alanı</label>',
    '<label>Görüşme Tarihi</label>': '<label data-i18n="contact.form.l_date">Görüşme Tarihi</label>',
    '<button type="submit" class="btn btn-primary" style="width: 100%;">Görüşme Talebi Gönder</button>': '<button type="submit" class="btn btn-primary" style="width: 100%;" data-i18n="contact.form.btn">Görüşme Talebi Gönder</button>',

    '<h4>StartBotAsistanı</h4>': '<h4 data-i18n="contact.bot.title">StartBotAsistanı</h4>',
    '<span>Bloke Hesap Miktarı</span>': '<span data-i18n="contact.bot.b1">Bloke Hesap Miktarı</span>',
    '<span>Ücretsiz BuT Desteği</span>': '<span data-i18n="contact.bot.b2">Ücretsiz BuT Desteği</span>',
    '<span>Adres & İletişim</span>': '<span data-i18n="contact.bot.b3">Adres & İletişim</span>',
    'placeholder="Sorunuzu buraya yazın..."': 'placeholder="Sorunuzu buraya yazın..." data-i18n-placeholder="contact.form.p_msg"',

    # Footer
    '<p>Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerinin okul başarısını artırırken, Türkiye\'den gelen adayların Almanya devlet üniversitesi başvurularını sıfır vize kaybı politikasıyla koordine eder.</p>': '<p data-i18n="footer.desc">Start Akademie, Frankfurt yakınlarındaki merkeziyle lise öğrencilerinin okul başarısını artırırken, Türkiye\'den gelen adayların Almanya devlet üniversitesi başvurularını sıfır vize kaybı politikasıyla koordine eder.</p>',
    '<h4>Hizmetler</h4>': '<h4 data-i18n="footer.services.title">Hizmetler</h4>',
    '<li><a href="#nachhilfe-details">Okul Ders Desteği (Nachhilfe)</a></li>': '<li><a href="#nachhilfe-details" data-i18n="footer.services.l1">Okul Ders Desteği (Nachhilfe)</a></li>',
    '<li><a href="#universities">Üniversite Danışmanlığı</a></li>': '<li><a href="#universities" data-i18n="footer.services.l2">Üniversite Danışmanlığı</a></li>',
    '<li><a href="#">Online Almanca Kursları</a></li>': '<li><a href="#" data-i18n="footer.services.l3">Online Almanca Kursları</a></li>',
    '<li><a href="#camp">Yaz Dil Kampları 2026</a></li>': '<li><a href="#camp" data-i18n="footer.services.l4">Yaz Dil Kampları 2026</a></li>',
    
    '<h4>Kurumsal</h4>': '<h4 data-i18n="footer.corporate.title">Kurumsal</h4>',
    '<li><a href="#">Genel Müdür: Mevlüt Uysal</a></li>': '<li><a href="#" data-i18n="footer.corporate.l1">Genel Müdür: Mevlüt Uysal</a></li>',
    '<li><a href="#">Etüt Merkezi: Bahnhofstraße 22</a></li>': '<li><a href="#" data-i18n="footer.corporate.l2">Etüt Merkezi: Bahnhofstraße 22</a></li>',
    '<li><a href="#">UG Adresi: Bahnhofstraße 22 / 22a</a></li>': '<li><a href="#" data-i18n="footer.corporate.l3">UG Adresi: Bahnhofstraße 22 / 22a</a></li>',
    '<li><a href="#">Instagram: @startakademie</a></li>': '<li><a href="#" data-i18n="footer.corporate.l4">Instagram: @startakademie</a></li>',
    
    '<h4>Yasal Bilgiler</h4>': '<h4 data-i18n="footer.legal.title">Yasal Bilgiler</h4>',
    '<li><a href="#">Impressum</a></li>': '<li><a href="#" data-i18n="footer.legal.l1">Impressum</a></li>',
    '<li><a href="#">Datenschutzerklärung</a></li>': '<li><a href="#" data-i18n="footer.legal.l2">Datenschutzerklärung</a></li>',
    '<li><a href="#">Anerkannter Lernförderanbieter</a></li>': '<li><a href="#" data-i18n="footer.legal.l3">Anerkannter Lernförderanbieter</a></li>',
    '<li><a href="#">Kreis Groß-Gerau Lisansı</a></li>': '<li><a href="#" data-i18n="footer.legal.l4">Kreis Groß-Gerau Lisansı</a></li>',
    
    '<p>© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.</p>': '<p data-i18n="footer.copy">© 2026 Start Akademie UG (haftungsbeschränkt). Tüm hakları saklıdır.</p>',
    '<a href="#">Gizlilik Sözleşmesi</a>': '<a href="#" data-i18n="footer.privacy">Gizlilik Sözleşmesi</a>',
    '<a href="#">Kullanım Koşulları</a>': '<a href="#" data-i18n="footer.terms">Kullanım Koşulları</a>',
}

with codecs.open('index.html', 'r', encoding='utf-8') as f:
    html = f.read()

for k, v in html_replacements.items():
    html = html.replace(k, v)

with codecs.open('index.html', 'w', encoding='utf-8') as f:
    f.write(html)

print("Final comprehensive translations injected successfully.")
